### PR TITLE
apphook: fix g_thread_init call order issue with older glibs

### LINKED ISSUE #2848: GLib-ERROR **: The thread system is not yet initialized.
## Version of syslog-ng

```
syslog-ng 3 (3.22.1)
Config version: 3.22
Installer-Version: 3.22.1
Revision:
Compile-Date: Jul 29 2019 10:58:45
Module-Directory: /logs/lvapp/lib/syslog-ng
Module-Path: /logs/lvapp/lib/syslog-ng
Include-Path: /logs/lvapp/share/syslog-ng/include
Available-Modules: cef,linux-kmsg-format,confgen,xml,map-value-pairs,kafka,graphite,csvparser,afsocket,pseudofile,afstomp,cryptofuncs,tfgetent,json-plugin,date,mod-python,appmodel,afuser,system-source,disk-buffer,basicfuncs,afprog,examples,hook-commands,syslogformat,snmptrapd-parser,affile,stardate,tags-parser,kvformat,add-contextual-data,dbparser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: off
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```

## Platform

Red Hat Enterprise Linux Server release 6.6 (Santiago)

## Debug bundle
```
$ sbin/syslog-ng-debun -r -R /logs/lvapp/
Syslog-NG DEBUg buNdle generator
Start environment detection
No syslog-ng detected
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.6 (Santiago)
Release:        6.6
Codename:       Santiago

Operating System Name: Linux

Redhat specific checks
Check package files integrity
package syslog-ng-premium-edition is not installed
package syslog-ng-premium-edition-client is not installed
package syslog-ng-premium-edition-compact is not installed
No syslog-ng RPM packages have been found!
list syslog-related packages

Start general info collection
System's full uname: Linux rhel6jb 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Getting network-interface information: Success
Getting network routes: Success
Getting DNS resolution-related information: Done
List all processes
Mount and disk free info collection

Start Syslog-specific info collection
Copy configs from /nonexistent
sbin/syslog-ng-debun: line 640: cd: /nonexistent: No such file or directory
112785 blocks
Error connecting control socket, socket='/logs/lvapp/var/syslog-ng.ctl', error='No such file or directory'
Gathering PKI information... sbin/syslog-ng-debun: line 616: cd: /nonexistent: No such file or directory
done.
cat: /logs/lvapp//var/run/syslog-ng.pid: No such file or directory
SVpid:  SNGpid:  Chpids:
sbin/syslog-ng-debun: line 686: /etc/init.d/syslog-ng: No such file or directory
Syslog-ng's exact version: syslog-ng 3 (3.22.1)
/logs/lvapp//sbin/syslog-ng-ctl stats
/logs/lvapp//sbin/syslog-ng-ctl query get *
/logs/lvapp//sbin/syslog-ng-ctl show-license-info
/logs/lvapp//sbin/syslog-ng-ctl credentials status

GLib-ERROR **: The thread system is not yet initialized.
aborting...
sbin/syslog-ng-debun: line 709: 26059 Aborted                 (core dumped) $syslogbin -s --preprocess-into "${tmpdir}/syslog.pp.conf"
0 blocks
Detecting init system: falling back to SystemV init style...
cp: cannot stat `/etc/init.d/syslog-ng': No such file or directory
chmod: cannot access `/tmp/syslog.debun.rhel6jb.2019-07-29_11-33.24865/sys.startup.init.syslog-ng': No such file or directory
sbin/syslog-ng-debun: line 294: /etc/init.d/syslog-ng: No such file or directory
Generating second batch of statistics
/logs/lvapp//sbin/syslog-ng-ctl stats
/logs/lvapp//sbin/syslog-ng-ctl query get *

Generating hashes... done.
Debug Bundle generation: Done.
Terminating live message watcher: sbin/syslog-ng-debun: line 273: 24873 Terminated              tail -f ${tmpdir}/syslog-ng.debun.txt 1>&3  (wd: /logs/lvapp)

```

# Issue

## Failure

(Backtrace, error messages or detailed description of failure comes here.)
(To create debug bundles, use `syslog-ng-debun`. Details of its usage can be found [on the documentation page](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/syslog-ng-debun.1.html))

```
(gdb) run
Starting program: /logs/lvapp/sbin/syslog-ng
[Thread debugging using libthread_db enabled]
Detaching after fork from child process 24858.

GLib-ERROR **: The thread system is not yet initialized.
aborting...

Program exited with code 01.

```

## Steps to reproduce

1. start syslog-ng with default config file

2. syslog-ng crashes : 

GLib-ERROR **: The thread system is not yet initialized.
aborting...

## Configuration

```
[root@rhel6jb lvapp]# cat etc/syslog-ng.conf
#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages.
#

@version: 3.22
@include "scl.conf"

source s_local {
        system();
        internal();
};

source s_network {
        default-network-drivers(
                # NOTE: TLS support
                #
                # the default-network-drivers() source driver opens the TLS
                # enabled ports as well, however without an actual key/cert
                # pair they will not operate and syslog-ng would display a
                # warning at startup.
                #
                #tls(key-file("/path/to/ssl-private-key") cert-file("/path/to/ssl-cert"))
        );
};

destination d_local {
        file("/var/log/messages");
        file("/var/log/messages-kv.log" template("$ISODATE $HOST $(format-welf --scope all-nv-pairs)\n") frac-digits(3));
};

log {
        source(s_local);

        # uncomment this line to open port 514 to receive messages
        #source(s_network);
        destination(d_local);
};
```

### PR DESCRIPTION
**Pull request by gaborznagy**
Recently, in app-startup() the g_cond_new() call preceded g_thread_init() call,
which only causes issues with glib versions older than 2.32, where it is not deprecated.

Fixes #2848

### CODE REVIEW

File: lib/apphook.c [hunk 1]
```diff
@@ -151,11 +151,11 @@ construct_nondumpable_logger(msg_fatal);
 void
 app_startup(void)
 {
+  g_thread_init(NULL);
   main_loop_thread_resource_init();
   msg_init(FALSE);
   iv_set_fatal_msg_handler(app_fatal);
   iv_init();
-  g_thread_init(NULL);
   crypto_init();
```
Comment (bazsi) [inline lib/apphook.c]: I would rather move the mainloop initialization call after g_thread_init()

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: lib/apphook.c (hunk 1 above)
Comment (gaborznagy) [reply lib/apphook.c]: Do you recommend a different order, than 1. g_thread_init(), 2. main_loop_thread_resource_init()?

Comment (gaborznagy) [reply lib/apphook.c]: Oh I think I got it: you mean move the calling of `main_loop_thread_resource_init()` instead of the `g_thread_init()`.
Can you explain the reason, please?

**Comment by bazsi** [comment]
The resource init call was the latest addition, and even at that point it
felt early. Getting the base functions in place (logging for instance)
earlier than higher level APIs seems better.

Early startup is tricky and fragile and initializing stuff at the latest
possible point at least reveals potential dependencies. Putting stuff last
is always preferred over putting stuff first.

**Comment by gaborznagy** [comment]
@bazsi, thanks for the explanation.
I need to check dependencies, as based on commits `main_loop_thread_resource_init()` had been put early in app_startup as it had to precede `stats_init()`.

I hope there is some flexibility inside app_startp, so resolving it will be easier.

**Comment by gaborznagy** [comment]
BTW, except RHEL/Centos 6 all major distributions use 2.4X or higher version of glib, e.g. Centos 7 has 2.56.1.

File: lib/apphook.c (hunk 1 above)
Comment (gaborznagy) [reply lib/apphook.c]: OK,. I've moved both functions just before `stats_init()`.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
Milestone added.
