### PR TITLE
loggen: paramter handling

### LINKED ISSUE #2239: loggen does not start with -D /dev/log (2 arguments)
# syslog-ng

## Version of syslog-ng

```
since 3.16.1
```

# Issue

## Failure

It won't start because it excepts 3 argument, but in this case 2 should be enough.

## Steps to reproduce

1. start loggen with `-D /dev/log` arguments

## Input and output logs

```
error [loggen.c:main:454] please specify target and port at least
```

Just an idea but each plugin could register an option, and if that is supplied that plugin could be started, and such checks like it has every options could be made plugin/option specific.

### PR DESCRIPTION
**Pull request by norberttak**
Move the parameter count check into plugins.
This allow us to run plugin options which
doesn't need target and port port parameters.
Fixes #2239

Signed-off-by: norberttakacs <norbert.takacs@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: tests/loggen/socket_plugin/socket_plugin.c [hunk 1]
```diff
@@ -308,9 +318,19 @@ active_thread_func(gpointer user_data)
...
+      if (!option->target)
+        ERROR("please specify target parameter\n");
+
+      fd = connect_unix_domain_socket(sock_type, option->target);
+    }
   else
-    fd = connect_ip_socket(sock_type, option->target, option->port, option->use_ipv6);
+    {
+      if (!option->target || !option->port)
+        ERROR("please specify target and port parameters\n");
```
Comment (MrAnno) [inline tests/loggen/socket_plugin/socket_plugin.c]: This validation should not be duplicated, it has nothing to do with active or idle threads IMHO.

The validation is based only on command line parameters and flags (`unix_socket_x` for example), so they can be checked before initializing threads/other functionality.

`start()` might be a better place, but adding a new method to the plugin interface is also an option (you already have `get_options_list`, something like `bool validate_options(PluginOption, GError**)` looks good to me).

File: tests/loggen/ssl_plugin/ssl_plugin.c [hunk 2]
```diff
@@ -296,6 +299,9 @@ active_thread_func(gpointer user_data)
   PluginOption *option = thread_context->option;
 
   char *message = g_malloc0(MAX_MESSAGE_LENGTH+1);
+
+  if (!option->target || !option->port)
+    ERROR("please specify target and port parameters\n");
```
Comment (MrAnno) [inline tests/loggen/ssl_plugin/ssl_plugin.c]: See my last comment.

File: tests/loggen/socket_plugin/socket_plugin.c (hunk 1 above)
Comment (norberttak) [reply tests/loggen/socket_plugin/socket_plugin.c]: I moved the check into start function

File: tests/loggen/ssl_plugin/ssl_plugin.c (hunk 2 above)
Comment (norberttak) [reply tests/loggen/ssl_plugin/ssl_plugin.c]: I moved the check into start function

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: tests/loggen/ssl_plugin/ssl_plugin.c (hunk 2 above)
Comment (MrAnno) [reply tests/loggen/ssl_plugin/ssl_plugin.c]: Thanks.
