### PR TITLE
F/searchguard

### LINKED ISSUE #1221: elasticsearch2: add support for searchguard2
We would like to use [searchguard2](https://github.com/floragunncom/search-guard) as an alternative to shield. Any of the following options should be available:
1. Using `client-mode(http)` provided https is possible
2. Using `client-mode(node)` [should work](/floragunncom/search-guard/issues/128)
3. Using transport mode: this seems to be pushed by elastic in favor of node/client (sensed to be deprecated in the near future)

I already tested 1. but I'm getting the following sg error: `SSL Problem Received fatal alert: certificate_unknown`

I also tested 2. using the following config (using `elasticsearch2(resource("/path/to/elasticsearch.yml")))

```

---
cluster:
  name: elasticsearch
node:
  client: true
  name: syslog_ng
path:
  data: /tmp
  home: /tmp
http:
  enabled: false
searchguard:
  ssl:
    transport:
      enabled: true
      keystore_filepath: "/etc/syslog-ng/elasticsearch/node-1-keystore.jks"
      keystore_password: changeit
      truststore_filepath: "/etc/syslog-ng/elasticsearch/truststore.jks"
      truststore_password: changeit
      enforce_hostname_verification: false
    http:
      enabled: false
  audit:
    type: internal_elasticsearch
  authcz:
    admin_dn:
      - CN=sgadmin
```

Here's the error message:

```
[WARN ][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] [T-Ray] Someone speaks plaintext instead of ssl, will close the channel
```

Maybe @floragunncom could kindly comment?

Thanks!

### PR DESCRIPTION
**Pull request by faxm0dem**
WIP: implements an additional `client-mode(searchguard)`

this was tested against searchguard 2.4.0.6 and searchguard-ssl 2.4.0.16

```
destination d_elastic {
  elasticsearch2(
    client-lib-dir("/usr/share/elasticsearch/lib/*.jar:/tmp/all-sg-jars/")
    resource("/etc/syslog-ng/elasticsearch/elasticsearch.yml")
    client-mode("searchguard")
    port("9300")
    concurrent_requests("1")
    flush_limit("1")
    index("syslog-$YEAR.$MONTH")
    type("syslog")
    skip-cluster-health-check("yes")
    template("$(format-json -s all-nv-pairs -x __* -x tmp.* -x SOURCE -x PROGRAM -x MESSAGE -x PID -x HOST_FROM -x HOST -x LEGACY_MSGHDR -p uniqid=$UNIQID --rekey timestamp --add-prefix @ --rekey .classifier.* --add-prefix pdb --rekey .SDATA.auto.* --shift 12 --rekey .SDATA.* --shift 7 --rekey .* --shift 1)")
  );
};
```

``` yaml

---
cluster:
  name: elasticsearch
node:
  client: true
  name: syslog_ng
path:
  data: /tmp
  home: /tmp
http:
  enabled: false
searchguard:
  ssl:
    transport:
      enabled: true
      keystore_filepath: "/etc/syslog-ng/elasticsearch/node-1-keystore.jks"
      keystore_password: changeit
      truststore_filepath: "/etc/syslog-ng/elasticsearch/truststore.jks"
      truststore_password: changeit
      enforce_hostname_verification: false
    http:
      enabled: false
  audit:
    type: internal_elasticsearch
  authcz:
    admin_dn:
      - CN=sgadmin
      - "CN=node-0.example.com, OU=SSL, L=Test, C=DE"
```

This fixes #1221

### CODE REVIEW

**Comment by faxm0dem** [comment]
@floragunncom when running the client there is a warning:

```
'Search Guard 2' plugin is normally not needed on transport client nodes.
```

Can you please shed some light on that?

**Comment by floragunncom** [comment]
``'Search Guard 2' plugin is normally not needed on transport client nodes.`` means that "normally" the Search Guard SSL plugin is sufficient enough. Search Guard plugin itself it only needed if you want to perform actions regarding the configuration stored in the searchguard index (what you normally will not do). Can you confirm that Search Guard SSL plugin is sufficient?

**Comment by faxm0dem** [comment]
I understand! I will make the changes and test tomorrow. Many thanks for your review!

**Comment by faxm0dem** [comment]
I have no idea why one of the builds is failing

**Comment by lbudai** [comment]
@faxm0dem: thank you for working on this feature. Unfortunately I don't have enough time right now for supporting you, maybe on Friday...

**Comment by faxm0dem** [comment]
@lbudai do you think this is the way to go, or would it be preferable to extend the `transport` mode to allow for a list of ES plugins to be loaded?

**Comment by lbudai** [comment]
@faxm0dem: we upgraded the es client version from 2.2 to 2.4 in the gradle file (this is why your PR is conflicting)

**Comment by faxm0dem** [comment]
okay thanks. could you comment on my other question?

**Comment by faxm0dem** [comment]
okay, so let's keep this and later add an option to generic transport client

File: modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/ESClientFactory.java [hunk 1]
```diff
@@ -44,6 +45,9 @@ else if (client_type.equals(ElasticSearchOptions.CLIENT_MODE_SHIELD)) {
 		else if (client_type.equals(ElasticSearchOptions.CLIENT_MODE_HTTP)) {
 			return new ESHttpClient(options);
 		}
+		else if (client_type.equals(ElasticSearchOptions.CLIENT_MODE_SEARCHGUARD)) {
+      return new ESTransportSearchGuardClient(options);
```
Comment (lbudai) [inline modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/ESClientFactory.java]: Could you fix the indentation?

**Comment by faxm0dem** [comment]
* squashed all commits
* rebased to master
* addressed indentation

**Comment by lbudai** [comment]
@faxm0dem: thanks!
