### PR TITLE
Switch case default warning fixes

### LINKED ISSUE #1963: warning elimination: switch case default branch
As the result of #1302 we want to eliminate some special warnings. For this reason I open issues with the different warning types to split the problem into subtasks.

The resolution would be a PR that fixes the mentioned warnings, and - to defend against reintroducing such warnings - these kind of warnings should be added in the top level Makefile.am, to the end of AM_CFLAGS in the ENABLE_EXTRA_WARNINGS block. As travis transforms such warnings to errors, we can be sure no new warnings will be added in the future from these types.

This issue should cover the switch case default branch related warnings
```
     54 [-Wswitch-default]
```
(The numbers in the statistics are just an approximate)

Hint: extra warnings can be enabled with --enable-extra-warnings configure option.

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
Resolves #1963

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by gaborznagy** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by mehul-m-prajapati** [comment]
Hi @furiel .

I have done following changes,
1.  Added missing default statements in source code.
2. Added pragma to ignore warnings from yacc/lex/bison generate source files.

Please review it.

Thanks,
Mehul

File: lib/cfg-lexer-subst.c [hunk 1]
```diff
@@ -92,6 +92,8 @@ _track_string_state(CfgLexerSubst *self, CfgLexerStringTrackState last_state, co
       if (*p == '\'')
         return CLS_NOT_STRING;
       return CLS_WITHIN_QSTRING;
+    default:
```
Comment (furiel) [inline lib/cfg-lexer-subst.c]: In this case we are in a state machine. It is a fatal error to enter to the default state. Please add g_assert_not_reached() into the default branch.

File: lib/cfg-parser.c [hunk 2]
```diff
@@ -421,6 +421,8 @@ cfg_process_flag(CfgFlagHandler *handlers, gpointer base, const gchar *flag_)
               else
                 *field = (*field) & ~handler->param;
               return TRUE;
+            default:
```
Comment (furiel) [inline lib/cfg-parser.c]: Operation should be either SET or CLEAR. This should be g_assert_not_reached() again.

File: lib/logproto/logproto-multiline-server.c [hunk 3]
```diff
@@ -48,6 +48,9 @@ log_proto_multiline_server_new(LogTransport *transport,
                                                           options->garbage);
     case MLM_NONE:
       return log_proto_text_server_new(transport, &options->super);
+
+    default:
```
Comment (furiel) [inline lib/logproto/logproto-multiline-server.c]: This case should cover all constants for multiline options. This should be a g_assert_not_reached()

File: lib/template/macros.c [hunk 4]
```diff
@@ -570,6 +570,8 @@ log_macro_expand(GString *result, gint id, gboolean escape, const LogTemplateOpt
           length = format_zone_info(buf, sizeof(buf), zone_ofs);
           g_string_append_len(result, buf, length);
           break;
+        default:
```
Comment (furiel) [inline lib/template/macros.c]: This should cover all macro types. The default branch should indicate a bug. Please add g_assert_not_reached() here.

File: lib/template/templates.c [hunk 5]
```diff
@@ -162,6 +162,8 @@ log_template_append_format_with_context(LogTemplate *self, LogMessage **messages
           g_static_mutex_unlock(&self->arg_lock);
           break;
         }
+        default:
```
Comment (furiel) [inline lib/template/templates.c]: A template should be either a function, a macro or a value. This switch case should cover all these. Here we should use g_assert_not_reached().

File: modules/afsocket/socket-options-inet.c [hunk 6]
```diff
@@ -159,6 +159,8 @@ socket_options_inet_setup_socket(SocketOptions *s, gint fd, GSockAddr *addr, AFS
       break;
     }
 #endif
+    default:
```
Comment (furiel) [inline modules/afsocket/socket-options-inet.c]: IP address can be either ipv4 or ipv6. We should use g_assert_not_reached() here.

**Comment by kira-syslogng** [comment]
success

**Comment by mehul-m-prajapati** [comment]
Hi @furiel ,

Thanks for your valuable review comments. 
I got to know about insights of the code which I modified.

Regards,
Mehul

**Comment by furiel** [comment]
Cool thanks. I see I added my comments to wrong line thus github did not detect the change. I just remove those because they are not relevant anymore.

File: lib/block-ref-grammar.ym [hunk 7]
```diff
@@ -24,6 +24,7 @@
 
 %code requires {
 
+#pragma GCC diagnostic ignored "-Wswitch-default"
```
Comment (gaborznagy) [inline lib/block-ref-grammar.ym]: For now `--enable-extra-warnings` is turned off for clang, but I would like to avoid diversion between clang and gcc.
As far as I found out clang support gcc pragmas, but can you verify it too please?
Here is the documentation I found about clang and pragmas
https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-command-line-flags

Comment (mehul-m-prajapati) [reply lib/block-ref-grammar.ym]: Yes @gaborznagy. Clang supports gcc pragmas.

Thus, we should add one more line as ```#pragma clang diagnostic ignored "-Wswitch-default"```.

May I do the this change and commit ?

Comment (gaborznagy) [reply lib/block-ref-grammar.ym]: As clang support gcc pragmas we should not add an extra line with a clang pragma.
The second option you suggested should be used only if you would like to ignore warnings for specific lines instead of the whole file.

So what I suggest is to have gcc pragmas only.

Comment (mehul-m-prajapati) [reply lib/block-ref-grammar.ym]: Ok. I got the point.

**Comment by mehul-m-prajapati** [comment]
Hi @furiel ,

I have a doubt whether we should use,
```
#pragma GCC diagnostic ignored "-Wswitch-default"
```

**OR**

```
#pragma GCC diagnostic ignored \"-Wswitch-default\"
```

Which is correct according to you ?

Thanks,
Mehul

**Comment by furiel** [comment]
I believe we do not need to escape. The lexer should handle those blocks as verbatim. Did you run into some kind of trouble without escaping?

**Comment by mehul-m-prajapati** [comment]
Nope. I have not faced any trouble without escaping.
It works fine without escaping on machine ...

File: lib/template/macros.c [hunk 8]
```diff
@@ -570,6 +570,9 @@ log_macro_expand(GString *result, gint id, gboolean escape, const LogTemplateOpt
...
```
[the remark this answers is not in the document]
Comment (mehul-m-prajapati) [reply lib/template/macros.c]: So, this change is correct ...

File: modules/afamqp/afamqp.c [hunk 9]
```diff
@@ -348,6 +348,11 @@ afamqp_is_ok(AMQPDestDriver *self, const gchar *context, amqp_rpc_reply_t ret)
                     evt_tag_int("time_reopen", self->super.time_reopen));
           return FALSE;
         }
+    default:
```
Comment (gaborznagy) [inline modules/afamqp/afamqp.c]: Can you add the numeric value of the unknown reply type, please?
And replace the "unknown server error" message to something unique, please?
E.g. "unknown response type" or "unknown response code"

Comment (mehul-m-prajapati) [reply modules/afamqp/afamqp.c]: Done the mentioned changes..,

Comment (gaborznagy) [reply modules/afamqp/afamqp.c]: Thanks! Looks good to me.

**Comment by kira-syslogng** [comment]
success
