### PR TITLE
threaded-dest: Fix integer overflow

### LINKED ISSUE #2466: segfault in 3.18.1+ latest master
# syslog-ng
   * Consistently getting a segfault with http and load-balancing in the worker. We are ingesting into elasticsearch using native http. 
   * This bug is being hit after removing batch-timeout which essentially was doing reinit to the destination frequently & leaking memory (related ticket #2462). 
   * With this change, reaping of connections went down drastically (from ~1600 to 41 times in 10 hrs) and I was hoping this race condition won't get hit.

source revision number: 
```
commit 82a7a012353143314d8482b7f249e56367a4da59 (origin/master, origin/HEAD, master)
Merge: 42789ba97 0701ca590
Author: László Várady <3130044+MrAnno@users.noreply.github.com>
Date:   Thu Dec 6 16:12:33 2018 +0100
```
  
## Version of syslog-ng

```
syslog-ng 3 (3.18.1)
Config version: 3.18
Installer-Version: 3.18.1
Revision: 
Compile-Date: Dec 12 2018 08:22:17
Module-Directory: /opt/syslog-ng-dbg/lib/syslog-ng
Module-Path: /opt/syslog-ng-dbg/lib/syslog-ng
Include-Path: /opt/syslog-ng-dbg/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,examples,graphite,hook-commands,http,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,mod-java,mod-python,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,xml
Enable-Debug: on
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

CentOS 7 (with ubuntu-bionic inside docker container) 

## Debug bundle
[syslog.debun.syslogng-1.2018-12-12_12-34.521.tar.gz](https://github.com/balabit/syslog-ng/files/2679422/syslog.debun.syslogng-1.2018-12-12_12-34.521.tar.gz)

# Issue
The process terminates after a segmentation fault when run over a prolonged period of time ~10 hrs.

## Failure

dmesg logs the following error.
```
[Wed Dec 12 17:37:49 2018] syslog-ng[19395]: segfault at 0 ip 00007fc35b520925 sp 00007fc304cb4b40 error 4
[Wed Dec 12 17:37:49 2018]  in libsyslog-ng-3.18.so.0.0.0[7fc35b4d1000+fc000]
[Wed Dec 12 17:37:49 2018]  in libsyslog-ng-3.18.so.0.0.0[7fc35b4d1000+fc000]
[Wed Dec 12 17:38:55 2018] syslog-ng[19366]: segfault at 0 ip 00007f486efda925 sp 00007f4815670b40 error 4
[Wed Dec 12 17:38:55 2018] syslog-ng[19179]: segfault at 0 ip 00007f486efda925 sp 00007f481b7f2bf0 error 4
[Wed Dec 12 17:38:55 2018] syslog-ng[19316]: segfault at 0 ip 00007f486efda925 sp 00007f481fffbbf0 error 4
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018] syslog-ng[19348]: segfault at 0 ip 00007f486efda925 sp 00007f481e7f8bf0 error 4
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018] syslog-ng[19178]: segfault at 0 ip 00007f486efda925 sp 00007f481d7f6b40 error 4
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018] syslog-ng[19623]: segfault at 0 ip 00007f486efda925 sp 00007f4816e73b40 error 4
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:38:55 2018]  in libsyslog-ng-3.18.so.0.0.0[7f486ef8b000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[18881]: segfault at 0 ip 00007f5a5495b925 sp 00007f5a03bafb40 error 4
[Wed Dec 12 17:39:46 2018] syslog-ng[19249]: segfault at 0 ip 00007f5a5495b925 sp 00007f5a023acb40 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19050]: segfault at 0 ip 00007f5a5495b925 sp 00007f59fd06cbf0 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19175]: segfault at 0 ip 00007f5a5495b925 sp 00007f59fc86bb40 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19376]: segfault at 0 ip 00007f5a5495b925 sp 00007f5a043b0b40 error 4
[Wed Dec 12 17:39:46 2018]  in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19048]: segfault at 0 ip 00007f5a5495b925 sp 00007f59fd86db40 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19144]: segfault at 51 ip 00007f5a5495b925 sp 00007f59fe06eb40 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018] syslog-ng[19274]: segfault at 0 ip 00007f5a5495b925 sp 00007f5a053b2bf0 error 4 in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Wed Dec 12 17:39:46 2018]  in libsyslog-ng-3.18.so.0.0.0[7f5a5490c000+fc000]
[Thu Dec 13 00:11:54 2018] syslog-ng[31818]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd771fa1b40 error 4
[Thu Dec 13 00:11:54 2018] syslog-ng[32733]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd76cbf8b40 error 4
[Thu Dec 13 00:11:54 2018]  in libsyslog-ng-3.18.so.0.0.0[7fd7c3d04000+fc000]
[Thu Dec 13 00:11:54 2018] syslog-ng[32537]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd774fa7b40 error 4
[Thu Dec 13 00:11:54 2018] syslog-ng[32808]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd775fa9b40 error 4
[Thu Dec 13 00:11:54 2018]  in libsyslog-ng-3.18.so.0.0.0[7fd7c3d04000+fc000]
[Thu Dec 13 00:11:54 2018]  in libsyslog-ng-3.18.so.0.0.0[7fd7c3d04000+fc000]
[Thu Dec 13 00:11:54 2018] syslog-ng[32866]: segfault at 0 ip 00007fd7c3d53925 sp 00007fd6b37fab40 error 4
[Thu Dec 13 00:11:54 2018]  in libsyslog-ng-3.18.so.0.0.0[7fd7c3d04000+fc000]
```

if I am applying the offset correctly, ```addr2line``` points me like below
```
xx@yy:/source# addr2line -e /opt/syslog-ng-dbg/lib/libsyslog-ng.so -Cfia 0x4F925                       
0x000000000004f925
log_threaded_dest_driver_queue
/source/lib/logthrdestdrv.c:884
xx@yy:/source# addr2line -e /opt/syslog-ng-dbg/lib/libsyslog-ng.so -Cfi 0x4F925                        
log_threaded_dest_driver_queue
/source/lib/logthrdestdrv.c:884
xx@yy:/source# addr2line -e /opt/syslog-ng-dbg/lib/libsyslog-ng.so  0x4F925                           
/source/lib/logthrdestdrv.c:884
```

AFAI understand, in the exception line marked with '>>>'.  ```dw->queue```  might point to an invalid address while the queue is being freed by the 'destination timeout, reaping' sequence and thus results into segv.

```
static void
log_threaded_dest_driver_queue(LogPipe *s, LogMessage *msg,
                               const LogPathOptions *path_options)
{
.....
  LogThreadedDestWorker *dw = _lookup_worker(self, msg);
.....
  >>> log_queue_push_tail(dw->queue, log_msg_ref(msg), path_options);  <<<
....
}
```

The reaping may reduce the queue refcount to zero ?
```
static void
affile_dd_reap_writer(AFFileDestDriver *self, AFFileDestWriter *dw)
{
  LogWriter *writer = (LogWriter *)dw->writer;

  main_loop_assert_main_thread();

  if (self->filename_is_a_template)
    {
      /* remove from hash table */
      g_hash_table_remove(self->writer_hash, dw->filename);
    }
  else
    {
      g_assert(dw == self->single_writer);
      self->single_writer = NULL;
    }

  LogQueue *queue = log_writer_get_queue(writer);
  log_pipe_deinit(&dw->super);
>>>>  log_dest_driver_release_queue(&self->super, queue);
  log_pipe_unref(&dw->super);
}
```
should we invoke ```log_queue_ref``` around ```dw->queue``` in order to avoid getting release inadvertently ? Please suggest .

## Steps to reproduce

1. start syslog-ng

2. With below configuration, spawn couple of containers and push 300k msgs/sec 200 bytes each log message and ingest it into elasticsearch. Observe when ES pushes back.

## Configuration

```
@version: 3.18
@include "scl.conf"

options { 
        use_dns(no); use_fqdn(no);
        owner("root"); group("adm"); perm(0640);
        chain_hostnames(off);
        bad_hostname("^gconfd$");
        keep_hostname(yes);
        create_dirs(yes);
        flush_lines(10);
        stats_freq (300);
        stats_level(1);
        stats-max-dynamics(5);
        time_reap (120);
        log_fifo_size (10000);
        time_reopen (10);
};



########################
# Sources
########################
# This is the default behavior of sysklogd package
# Logs may come from unix stream, but not from another machine.
#
source s_src {
       #https://tinyurl.com/qj6f983
       #system();
       internal();
};

source network1  { syslog(transport(udp) port(`SRC_PORT1`) log_fetch_limit(2000));};
source network2  { syslog(transport(udp) port(`SRC_PORT2`) log_fetch_limit(2000));};
source network3  { syslog(transport(udp) port(`SRC_PORT3`) log_fetch_limit(2000));};
source network4  { syslog(transport(udp) port(`SRC_PORT4`) log_fetch_limit(2000));};
source network5  { syslog(transport(udp) port(`SRC_PORT5`) log_fetch_limit(2000));};
source network6  { syslog(transport(udp) port(`SRC_PORT6`) log_fetch_limit(2000));};
source network7  { syslog(transport(udp) port(`SRC_PORT7`) log_fetch_limit(2000));};
source network8  { syslog(transport(udp) port(`SRC_PORT8`) log_fetch_limit(2000));};
source network9  { syslog(transport(udp) port(`SRC_PORT9`) log_fetch_limit(2000));};
source network10 { syslog(transport(udp) port(`SRC_PORT10`) log_fetch_limit(2000));};
source network11 { syslog(transport(udp) port(`SRC_PORT11`) log_fetch_limit(2000));};
source network12 { syslog(transport(udp) port(`SRC_PORT12`) log_fetch_limit(2000));};


########################
# Destinations
########################
# First some standard logfile

destination d_syslog { file("`SYSNG_CONTAINER_LOGPATH`/syslog-ng-`SRC_PORT1`.log"); };

# The root's console.
#
destination d_console { usertty("root"); };

# Virtual console.
#
#destination d_console_all { file(`tty10`); };

########################
# Filters
########################

filter f_syslog3 { not facility(auth, authpriv, mail);  };

parser pattern_db {
  db-parser(
    file("/etc/syslog-ng/patterndb.xml")
    drop-unmatched(yes)
  );
};
rewrite add_prog{set("Traffic", value("PROGRAM"));};


##### Elasticsearch destination

block destination elasticsearchhttp(server("localhost:9200") persistname("http-persist") ) {
  http(
      persist-name("`persistname`")
       url( "http://10.176.1.xx:9201/generator-latest/traffic/_bulk"
          ,"http://10.176.1.xx:9202/generator-latest/traffic/_bulk"
          ,"http://10.176.1.xx:9203/generator-latest/traffic/_bulk"
          ,"http://10.176.1.xx:9204/generator-latest/traffic/_bulk")
      timeout(120)
      method("POST")
      flush-lines(500)
      flush-bytes(512Kb)
      flush-timeout(100)
      workers(8)
      headers("Content-Type: application/x-ndjson")
      body-suffix("\n")
      body('{ "index":{} }
           $(format-json --scope nv_pairs --exclude DATE --key ISODATE @timestamp=${ISODATE})')
 );
};

destination http1  { elasticsearchhttp(server("10.176.5.xxx:9201") persistname("http-persist-`SRC_PORT1`") );  };
destination http2  { elasticsearchhttp(server("10.176.5.xxx:9202") persistname("http-persist-`SRC_PORT2`") );  };
destination http3  { elasticsearchhttp(server("10.176.5.xxx:9203") persistname("http-persist-`SRC_PORT3`") );  };
destination http4  { elasticsearchhttp(server("10.176.5.xxx:9204") persistname("http-persist-`SRC_PORT4`") );  };
destination http5  { elasticsearchhttp(server("10.176.5.xxx:9201") persistname("http-persist-`SRC_PORT5`") );  };
destination http6  { elasticsearchhttp(server("10.176.5.xxx:9202") persistname("http-persist-`SRC_PORT6`") );  };
destination http7  { elasticsearchhttp(server("10.176.5.xxx:9203") persistname("http-persist-`SRC_PORT7`") );  };
destination http8  { elasticsearchhttp(server("10.176.5.xxx:9204") persistname("http-persist-`SRC_PORT8`") );  };
destination http9  { elasticsearchhttp(server("10.176.5.xxx:9201") persistname("http-persist-`SRC_PORT9`") );  };
destination http10 { elasticsearchhttp(server("10.176.5.xxx:9202") persistname("http-persist-`SRC_PORT10`") );  };
destination http11 { elasticsearchhttp(server("10.176.5.xxx:9203") persistname("http-persist-`SRC_PORT11`") );  };
destination http12 { elasticsearchhttp(server("10.176.5.xxx:9204") persistname("http-persist-`SRC_PORT12`") );  };


########################
# Log paths
########################


log { source(s_src); filter(f_syslog3); destination(d_syslog); flags(final); };

log { source(network1); rewrite(add_prog); parser(pattern_db); destination(http1); flags(final); };
log { source(network2); rewrite(add_prog); parser(pattern_db); destination(http2); flags(final); };
log { source(network3); rewrite(add_prog); parser(pattern_db); destination(http3); flags(final); };
log { source(network4); rewrite(add_prog); parser(pattern_db); destination(http4); flags(final); };
log { source(network5); rewrite(add_prog); parser(pattern_db); destination(http5); flags(final); };
log { source(network6); rewrite(add_prog); parser(pattern_db); destination(http6); flags(final); };
log { source(network7); rewrite(add_prog); parser(pattern_db); destination(http7); flags(final); };
log { source(network8); rewrite(add_prog); parser(pattern_db); destination(http8); flags(final); };
log { source(network9); rewrite(add_prog); parser(pattern_db); destination(http9); flags(final); };
log { source(network10); rewrite(add_prog); parser(pattern_db); destination(http10); flags(final); };
log { source(network11); rewrite(add_prog); parser(pattern_db); destination(http11); flags(final); };
log { source(network12); rewrite(add_prog); parser(pattern_db); destination(http12); flags(final); };


```

(or gist URL)

### PR DESCRIPTION
**Pull request by alltilla**
A negative number's modulo will be negative, which in our case pointed to a negative entry of the workers array, causing segfault.

Fixes #2466.

Signed-off-by: Attila Szakacs <attila.szakacs@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: lib/logthrdestdrv.c [hunk 1]
```diff
@@ -860,7 +860,7 @@ log_threaded_dest_driver_set_max_retries(LogDriver *s, gint max_retries)
 LogThreadedDestWorker *
 _lookup_worker(LogThreadedDestDriver *self, LogMessage *msg)
 {
-  static gint last_worker = 0;
+  static guint last_worker = 0;
```
Comment (MrAnno) [inline lib/logthrdestdrv.c]: 👍 

A question:
Why is it global? Shouldn't this be stored in `LogThreadedDestDriver`?

Comment (furiel) [reply lib/logthrdestdrv.c]: Personally I like it being static. This way it has even smaller scope than `LogThreadedDestDriver`.

Comment (furiel) [reply lib/logthrdestdrv.c]: **smaller=in terms of lexical scope

Comment (furiel) [reply lib/logthrdestdrv.c]: Oh ok I am speaking green. This means if we have two http destinations, one message arriving to the first will step the current worker in the second. Thats unfortunate indeed.

Comment (MrAnno) [reply lib/logthrdestdrv.c]: Yes, the name is only available locally, but the storage is global.

It can not be tested easily, and we should not really use it across threads, which I think we do. This runs in the source thread, and all threaded destination drivers share one common value of this (if I'm not mistaken). Correct me if I'm wrong, but I don't think this is correct at all.

Comment (MrAnno) [reply lib/logthrdestdrv.c]: Since it runs in multiple source threads, I'd also consider making it atomic.

**Comment by MrAnno** [comment]
I've dismissed my review, because in my understanding, `last_worker` has to be atomic and not global in order to avoid invalid indexing.

File: lib/logthrdestdrv.c (hunk 1 above)
Comment (furiel) [reply lib/logthrdestdrv.c]: I agree this should be moved into the dest driver. But why do we need to make it atomic? Once moved into destdriver, in case of non-atomic access, I think the worst thing that can happen is the distribution will not be entirely uniform (during high load), but I believe it is acceptable.

Comment (MrAnno) [reply lib/logthrdestdrv.c]: AFAIK it's undefined if 2 variables are written at the same time, so might get out-of-range values if the assignment is not atomic. Incrementing the value by one is most probably atomic on all known platlform, but I would not rely on that.

Comment (bazsi) [reply lib/logthrdestdrv.c]: The static keyword was only a PoC for doing round robin, I shouldn't have left it there, neither the signed type. Sorry.

I'd argue that atomic access is not needed though. The worst can happen is a lost update (e.g. two threads using the same value) or a value that is skipped. And in any case we would be doing a modulo after that, which should constrain the value in the required boundaries.

**Comment by furiel** [comment]
@bazsi @MrAnno what do you think about the `static gchar persist_name[1024];` in `_format_queue_persist_name`? That information is used to assign a queue to the worker.

 That function is called in `log_threaded_dest_worker_init_method`, which is called in `log_threaded_dest_worker_thread_init`, that runs in the worker thread. Should we address that `static` as well?

**Comment by MrAnno** [comment]
I think we should address that one as well. Unfortunately, `persist_name` is not read-only, and the init methods of the workers are not called sequentially.

We could add an output buffer parameter to `_format_queue_persist_name`, which can be allocated on the stack in `log_threaded_dest_worker_init_method`, so you don't have to embed the persist_name in `LogThreadedDestWorker`.

**Comment by MrAnno** [comment]
I think `_format_queue_persist_name()` is a bit different than other occurrences. It does not return the same string, `worker_index` is used there, which might be a real problem if it's overwritten by another worker thread.

I've checked other occurences, afsocket, for example, seems to be correct to me (`afsocket_sd_format_connections_name`), because the format method is called carefully from one thread, sequentially.

> we could probably do much better, however I think that can go to a separate PR, and this should go in separately.

I agree, sorry for spamming this PR. :)

**Comment by kira-syslogng** [comment]
Build SUCCESS
