### PR TITLE
Fix frequent disconnects of syslog() with TLS

### LINKED ISSUE #2328: Frequent disconnects with openssl 1.1.1 and TLS connections
## Version of syslog-ng

```
syslog-ng 3 (3.17.2)
Config version: 3.17
Installer-Version: 3.17.2
Revision: 
Compile-Date: Sep 10 2018 19:53:00
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Error opening plugin module; module='afmongodb', error='libmongoc-1.0.so.0: cannot open shared object file: No such file or directory'
Error opening plugin module; module='afamqp', error='librabbitmq.so.4: cannot open shared object file: No such file or directory'
Error opening plugin module; module='redis', error='libhiredis.so.0.13: cannot open shared object file: No such file or directory'
Error opening plugin module; module='afsmtp', error='libesmtp.so.6: cannot open shared object file: No such file or directory'
Available-Modules: afstomp,json-plugin,map-value-pairs,graphite,afsql,basicfuncs,snmptrapd-parser,disk-buffer,confgen,affile,dbparser,tfgetent,sdjournal,hook-commands,afsocket,afuser,afprog,mod-python,linux-kmsg-format,kvformat,cef,syslogformat,pseudofile,system-source,stardate,xml,http,cryptofuncs,tags-parser,date,add-contextual-data,csvparser,appmodel
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: on

```

## Platform

Arch Linux

## Failure

When the server is running with openssl 1.1.1 I get frequent disconnects on clients. When I downgrade openssl on the server to 1.1.0.i, the connections are stable. I'm guessing that this is related to openssl 1.1 supporting TLS 1.3.

Between each reconnect, the client still manages to transfer log data to the server, but afterwards it disconnects with the log output shown below.

I tried to disabled tls1.3, but it seems that `ssl-options` only allows to disable to up 1.2 and `no-tlsv13` is not an allowed argument. Forcing a 1.2 cipher suite on the server, such as `ECDHE-RSA-AES256-GCM-SHA384`, also does not seem to help.

## Steps to reproduce

Run syslog-ng with the configuration and openssl 1.1.1.

## Configuration

Server config:
```
@version: 3.17
@include "scl.conf"
#
# /etc/syslog-ng/syslog-ng.conf
#

options {
  stats_freq (0);
  flush_lines (0);
  time_reopen (10);
  log_fifo_size (10000);
  chain_hostnames (off);
  use_dns (no);
  use_fqdn (no);
  create_dirs (no);
  keep_hostname (yes);
  perm(0640);
  group("log");
};

source src {
  system();
  internal();
  udp();
};

source tls_syslog_source {
        syslog(ip(0.0.0.0) port(syslog-tls)
        transport("tls")
        tls(
                ca_dir("/etc/syslog-ng/cert.d")
                key-file("/etc/ssl/private/syslog.server-speed.net.key")
                cert-file("/etc/ssl/private/syslog.server-speed.net.crt")
        ));
};

#destination mistral { udp("192.168.4.1"); };
destination d_everything { file("/var/log/everything.log"); };
#log {source(src); destination(mistral); };
log { source(src); destination(d_everything); };
log { source(tls_syslog_source); destination(d_everything); };

```

Client config:
```
@version: 3.17
@include "scl.conf"
#
# /etc/syslog-ng/syslog-ng.conf
#

options {
  stats_freq (0);
  flush_lines (0);
  time_reopen (10);
  log_fifo_size (10000);
  chain_hostnames (off);
  use_dns (no);
  use_fqdn (no);
  create_dirs (no);
  keep_hostname (yes);
  perm(0640);
  group("log");
};

source src {
  system();
  internal();
  udp();
};

destination d_everything { file("/var/log/everything.log"); };
log { source(src); destination(d_everything); };

destination calima {syslog("syslog.server-speed.net" port(syslog-tls) transport("tls") tls(
        ca_dir("/etc/syslog-ng/cert.d")
        key-file("/etc/ssl/private/mistral.key")
        cert-file("/etc/ssl/private/mistral.crt")
));};
log {source(src); destination(calima); };
```

## logs

These logs are filtered to only include syslog-ng lines and no other application logs. 

server:
```
Oct  2 14:53:03 calima syslog-ng[4220]: Syslog connection accepted; fd='119', client='AF_INET(192.168.4.1:36031)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:03 calima syslog-ng[4220]: Error reading RFC5428 style framed data; fd='119', error='Connection reset by peer (104)'
Oct  2 14:53:03 calima syslog-ng[4220]: Syslog connection closed; fd='119', client='AF_INET(192.168.4.1:36031)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:10 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.103:38599)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:10 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.103:38599)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:10 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.113:44683)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:10 calima syslog-ng[4220]: Syslog connection accepted; fd='121', client='AF_INET(192.168.4.112:41523)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:10 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.113:44683)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:10 calima syslog-ng[4220]: Syslog connection closed; fd='121', client='AF_INET(192.168.4.112:41523)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:13 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.1:42587)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:13 calima syslog-ng[4220]: Error reading RFC5428 style framed data; fd='118', error='Connection reset by peer (104)'
Oct  2 14:53:13 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.1:42587)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:20 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.103:35049)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:20 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.103:35049)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:20 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.112:39013)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:20 calima syslog-ng[4220]: Syslog connection accepted; fd='121', client='AF_INET(192.168.4.113:38147)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:20 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.112:39013)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:20 calima syslog-ng[4220]: Syslog connection closed; fd='121', client='AF_INET(192.168.4.113:38147)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:23 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.1:37815)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:23 calima syslog-ng[4220]: Error reading RFC5428 style framed data; fd='118', error='Connection reset by peer (104)'
Oct  2 14:53:23 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.1:37815)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:30 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.103:34441)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:30 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.103:34441)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:30 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.112:41147)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:30 calima syslog-ng[4220]: Syslog connection accepted; fd='121', client='AF_INET(192.168.4.113:36259)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:30 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.112:41147)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:30 calima syslog-ng[4220]: Syslog connection closed; fd='121', client='AF_INET(192.168.4.113:36259)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:33 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.1:41311)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:33 calima syslog-ng[4220]: Error reading RFC5428 style framed data; fd='118', error='Connection reset by peer (104)'
Oct  2 14:53:33 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.1:41311)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:40 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.103:38473)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:40 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.103:38473)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:40 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.113:39433)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:40 calima syslog-ng[4220]: Syslog connection accepted; fd='121', client='AF_INET(192.168.4.112:38367)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:40 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.113:39433)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:40 calima syslog-ng[4220]: Syslog connection closed; fd='121', client='AF_INET(192.168.4.112:38367)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:43 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.1:40431)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:43 calima syslog-ng[4220]: Error reading RFC5428 style framed data; fd='118', error='Connection reset by peer (104)'
Oct  2 14:53:43 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.1:40431)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:50 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.103:39019)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:50 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.103:39019)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:50 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.113:35891)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:50 calima syslog-ng[4220]: Syslog connection accepted; fd='121', client='AF_INET(192.168.4.112:37643)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:50 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.113:35891)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:50 calima syslog-ng[4220]: Syslog connection closed; fd='121', client='AF_INET(192.168.4.112:37643)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:53 calima syslog-ng[4220]: Syslog connection accepted; fd='118', client='AF_INET(192.168.4.1:39199)', local='AF_INET(0.0.0.0:6514)'
Oct  2 14:53:53 calima syslog-ng[4220]: Error reading RFC5428 style framed data; fd='118', error='Connection reset by peer (104)'
Oct  2 14:53:53 calima syslog-ng[4220]: Syslog connection closed; fd='118', client='AF_INET(192.168.4.1:39199)', local='AF_INET(0.0.0.0:6514)'
```

client:
```
Oct  2 14:54:03 mistral syslog-ng[3104]: Syslog connection established; fd='52', server='AF_INET(192.168.4.111:6514)', local='AF_INET(0.0.0.0:0)'
Oct  2 14:54:03 mistral syslog-ng[3104]: EOF occurred while idle; fd='52'
Oct  2 14:54:03 mistral syslog-ng[3104]: Syslog connection closed; fd='52', server='AF_INET(192.168.4.111:6514)', time_reopen='10'
Oct  2 14:54:13 mistral syslog-ng[3104]: Syslog connection established; fd='52', server='AF_INET(192.168.4.111:6514)', local='AF_INET(0.0.0.0:0)'
Oct  2 14:54:13 mistral syslog-ng[3104]: EOF occurred while idle; fd='52'
Oct  2 14:54:13 mistral syslog-ng[3104]: Syslog connection closed; fd='52', server='AF_INET(192.168.4.111:6514)', time_reopen='10'
Oct  2 14:54:23 mistral syslog-ng[3104]: Syslog connection established; fd='52', server='AF_INET(192.168.4.111:6514)', local='AF_INET(0.0.0.0:0)'
Oct  2 14:54:23 mistral syslog-ng[3104]: EOF occurred while idle; fd='52'
Oct  2 14:54:23 mistral syslog-ng[3104]: Syslog connection closed; fd='52', server='AF_INET(192.168.4.111:6514)', time_reopen='10'
Oct  2 14:54:33 mistral syslog-ng[3104]: Syslog connection established; fd='52', server='AF_INET(192.168.4.111:6514)', local='AF_INET(0.0.0.0:0)'
Oct  2 14:54:33 mistral syslog-ng[3104]: EOF occurred while idle; fd='52'
Oct  2 14:54:33 mistral syslog-ng[3104]: Syslog connection closed; fd='52', server='AF_INET(192.168.4.111:6514)', time_reopen='10'
Oct  2 14:54:43 mistral syslog-ng[3104]: Syslog connection established; fd='52', server='AF_INET(192.168.4.111:6514)', local='AF_INET(0.0.0.0:0)'
Oct  2 14:54:43 mistral syslog-ng[3104]: EOF occurred while idle; fd='52'
Oct  2 14:54:43 mistral syslog-ng[3104]: Syslog connection closed; fd='52', server='AF_INET(192.168.4.111:6514)', time_reopen='10'
Oct  2 14:54:53 mistral syslog-ng[3104]: Syslog connection established; fd='52', server='AF_INET(192.168.4.111:6514)', local='AF_INET(0.0.0.0:0)'
Oct  2 14:54:53 mistral syslog-ng[3104]: EOF occurred while idle; fd='52'
Oct  2 14:54:53 mistral syslog-ng[3104]: Syslog connection closed; fd='52', server='AF_INET(192.168.4.111:6514)', time_reopen='10'
Oct  2 14:55:03 mistral syslog-ng[3104]: Syslog connection established; fd='52', server='AF_INET(192.168.4.111:6514)', local='AF_INET(0.0.0.0:0)'
Oct  2 14:55:03 mistral syslog-ng[3104]: EOF occurred while idle; fd='52'
Oct  2 14:55:03 mistral syslog-ng[3104]: Syslog connection closed; fd='52', server='AF_INET(192.168.4.111:6514)', time_reopen='10'
```

### PR DESCRIPTION
**Pull request by MrAnno**
`LW_DETECT_EOF` closes the connection when input is received from a destination socket.
This is only acceptable for one-way protocols. TLS is duplex, so it has to be disabled both in TLS-based streaming and RFC 6587-framed protocols.

I've also fixed an incorrect RFC reference in logproto.
RFC 5428 is about SNMP, I think RFC 6587 is what we've actually implemented (`syslog()`).

https://tools.ietf.org/html/rfc5428
https://tools.ietf.org/html/rfc6587

Fixes #2328

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
This is a very interesting PR!
It deals with a problem seen in another places where bidirectional protocol is expected: #1433

However this solution is specific to afinet/TLS and not a general solution for bidirectional protocols.
What's also a problem in #1433 is that there is no reading on the incoming side.
But I don't want to hijack the topic. :)

File: lib/logproto/tests/test-framed-server.c [hunk 1]
```diff
@@ -80,7 +80,7 @@ test_log_proto_framed_server_io_error(void)
               LTM_EOF),
             get_inited_proto_server_options());
   assert_proto_server_fetch(proto, "0123456789ABCDEF0123456789ABCDEF", -1);
-  assert_proto_server_fetch_failure(proto, LPS_ERROR, "Error reading RFC5428 style framed data");
+  assert_proto_server_fetch_failure(proto, LPS_ERROR, "Error reading RFC6587 style framed data");
```
Comment (gaborznagy) [inline lib/logproto/tests/test-framed-server.c]: Nice catch :)

Comment (MrAnno) [reply lib/logproto/tests/test-framed-server.c]: Thanks to @kira-syslogng 😄

**Comment by MrAnno** [comment]
@gaborznagy For #1433, the suggested `LW_IGNORE_INPUT` flag or a separate LogProtoClient implementation that reads and drops everything would be good IMHO.
