### PR TITLE
Dqtool relocate diskq

### LINKED ISSUE #1851: disq location cannot be modified
# syslog-ng

When setting up a destination with disk buffer, it is not possible to change the path anymore:

* changing the path in `syslog-ng.conf` and then reloading the config does not use the new path
* changing the path in `syslog-ng.conf` and then restarting syslog-ng does not use the new path

The only workaround I found was to delete the persist-file

## Version of syslog-ng

```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision:
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: cryptofuncs,syslogformat,system-source,curl,afstomp,graphite,kvformat,afamqp,date,cef,mod-java,pseudofile,confgen,afprog,riemann,add-contextual-data,affile,afsocket,mod-python,linux-kmsg-format,basicfuncs,geoip-plugin,disk-buffer,afuser,json-plugin,tfgetent,sdjournal,dbparser,afsmtp,csvparser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on

```

## Platform

CentOS Linux release 7.3.1611 (Core)

# Issue

## Steps to reproduce

1. start syslog-ng
2. change location of disq buffer
3. reload or restart syslog-ng
4. location of disq buffer is unchanged

## Configuration

```
destination {
  elasticsearch2(
    ...
    disk-buffer(reliable(no) dir("/var/lib/syslog-ng-disq-01/") disk-buf-size(53687091200) mem-buf-size(1073741824))
    ...
  );
};
```

### PR DESCRIPTION
**Pull request by lbudai**
Add `relocate` function to `dqtool`.
Fixes #1851

##### examples:
* relocate a single queue file:

```    
    bin/dqtool relocate --new_path /tmp/dq --persist var/syslog-ng.persist /tmp/syslog-ng-00000.rqf
```
    
* relocate multiple queue files

```
    bin/dqtool relocate --new_path /tmp/dq --persist var/syslog-ng.persist /tmp/syslog-ng-00000.rqf /tmp/syslog-ng-00000.qf
```
    
* relocate all queue files

```
    bin/dqtool relocate --new_path /tmp/dq --persist var/syslog-ng.persist --all
```

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by jszigetvari** [comment]
Cool stuff, I like it! (Although I am not a member of the strictly viewed dev team, so I don't feel that would be entitled to approve this.)

File: modules/diskq/dqtool.c [hunk 1]
```diff
@@ -241,12 +251,292 @@ _relocate_validate_options(void)
...
 
+  if (!g_threads_got_initialized)
+    {
+      g_thread_init(NULL);
+    }
+
+  main_thread_handle = get_thread_id();
+
+  PersistState *state = persist_state_new(persist_file_path);
+  persist_state_start_edit(state);
```
Comment (Kokan) [inline modules/diskq/dqtool.c]: Please handle if this function return with false.

File: modules/diskq/dqtool.c [hunk 2]
```diff
@@ -241,12 +251,292 @@ _relocate_validate_options(void)
...
+  return TRUE;
+}
+
+static gboolean
+_mmap_content_from_fd(gint fd, gchar **content, gsize *content_length)
+{
+  if (!_get_content_length_by_fd(fd, content_length))
+    return FALSE;
+
+  *content = mmap(NULL, *content_length, PROT_READ, MAP_PRIVATE, fd, 0);
```
Comment (Kokan) [inline modules/diskq/dqtool.c]: Mapping a diskq file twice could be troublesome. Why did you choose to use `mmap + memcpy` instead of traditional `read + write` from a file ?

Comment (furiel) [inline modules/diskq/dqtool.c]: I feel some risk here. Disk queue files might be large. Can we run into trouble mmaping gigabytes of ram? (I am thinking about ulimit).

File: modules/diskq/dqtool.c [hunk 3]
```diff
@@ -241,12 +251,292 @@ _relocate_validate_options(void)
...
+  gint rename_res = rename(from, to);
+
+  switch (rename_res)
+    {
+    case 0:
+      return TRUE;
+    case EXDEV:
+      return _move_file_between_different_filesystems(from, to);
+    default:
+      return FALSE;
```
Comment (Kokan) [inline modules/diskq/dqtool.c]: [optional] might help to write the cause of the error.

File: modules/diskq/dqtool.c [hunk 4]
```diff
@@ -241,12 +251,292 @@ _relocate_validate_options(void)
...
+static gboolean
+_move_file(const gchar *from, const gchar *to)
+{
+  gint rename_res = rename(from, to);
+
+  switch (rename_res)
+    {
+    case 0:
+      return TRUE;
+    case EXDEV:
```
Comment (furiel) [inline modules/diskq/dqtool.c]: `EXDEV` is and errno value. `rename_res` is still -1 in that case. (switch-case on wrong variable).

File: modules/diskq/dqtool.c [hunk 5]
```diff
@@ -241,12 +251,292 @@ _relocate_validate_options(void)
...
+    {
+      fprintf(stderr, "File reading error: %s\n", filename);
+      fclose(f);
+      return FALSE;
+    }
+
+  fclose(f);
+
+  idbuf[4] = '\0';
+  if (reliable && strcmp(idbuf, "SLRQ") != 0)
```
Comment (furiel) [inline modules/diskq/dqtool.c]: fread can return with less than 4, in that case some bytes of `idbuf` is undefined. It is better memset `idbuf` to zero.

File: modules/diskq/dqtool.c [hunk 6]
```diff
@@ -241,12 +251,292 @@ _relocate_validate_options(void)
...
+  if (!is_file_regular(value))
+    return FALSE;
+
+  return _file_is_diskq(value);
+}
+
+static gchar *
+_append_filename_to_dirname(const gchar *dirname, const gchar *filename)
+{
+  if (!dirname || !filename)
```
Comment (furiel) [inline modules/diskq/dqtool.c]: `g_build_filename` could work?

File: modules/diskq/dqtool.c [hunk 7]
```diff
@@ -241,12 +251,292 @@ _relocate_validate_options(void)
...
+      gchar *relocated_qfile = _append_filename_to_dirname(new_diskq_path, basename(qfile));
+      if (!relocated_qfile)
+        {
+          fprintf(stderr, "Invalid path. new_diskq_dir: %s, qfile: %s\n", new_diskq_path, qfile);
+          return;
+        }
+
+      if (_move_file(qfile, relocated_qfile))
+        {
+          printf("new qfile_path: %s\n", relocated_qfile);
```
Comment (furiel) [inline modules/diskq/dqtool.c]: As this is just a diagnostics log, it is better send to stderr.

File: modules/diskq/dqtool.c [hunk 8]
```diff
@@ -177,6 +203,343 @@ dqtool_info(int argc, char *argv[])
...
+    {
+      fprintf(stderr, "Error: %s\n", strerror(errno));
+      return FALSE;
+    }
+
+  return TRUE;
+}
+
+static gint
+_open_fd_for_writing(const gchar *fname)
```
Comment (furiel) [inline modules/diskq/dqtool.c]: [Optional]: The copy related functions clutter this file a little bit. I suggest adding them to a separate c file.

File: modules/diskq/dqtool.c (hunk 5 above)
Comment (lbudai) [reply modules/diskq/dqtool.c]: ...or just check if `fread` returned 4

File: modules/diskq/dqtool.c (hunk 2 above)
Comment (lbudai) [reply modules/diskq/dqtool.c]: `mmap` is an easy&good alternative for fread/fwrite, but well.. if someone limiting the address space (with `ulimit -v`) then this won't work (@Kokan : but it works even when you have a small amount of memory... so if you have 3GB of RAM, you can easily load a 6GB diskq file - and use a 12GB virt. address space).

`g_file_copy`: that uses gio (and currently we don't link to gio lib)
(or, `g_file_move`)

So if you don't like the `mmap` based copy, I can re-implement it to fread/fwrite, but won't/cannot use `g_file_copy`.

File: modules/diskq/dqtool.c (hunk 4 above)
Comment (lbudai) [reply modules/diskq/dqtool.c]: thx!

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: modules/diskq/dqtool.c [hunk 9]
```diff
@@ -241,12 +251,292 @@ _relocate_validate_options(void)
...
+    {
+      fprintf(stderr, "mmap failed, reason: %s\n", strerror(errno));
+      return FALSE;
+    }
+
+  return TRUE;
+}
+
+static gboolean
+_mmap_copy_to_fd(gint fd, gchar *content, gsize content_length)
```
[the remark this answers is not in the document]
Comment (furiel) [reply modules/diskq/dqtool.c]: As discussed IRL, g_file_copy() cannot work as we do not link to GIO. Not worth the effort.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by faxm0dem** [comment]
I'm sorry I didn't take the time to test this 🙏
