### PR TITLE
Fix double-free error in logproto unit tests

### LINKED ISSUE #2658: test_logproto failed to pass unit test due to double free error
## Version of syslog-ng
syslog-ng 3.20.1

## Platform
Fedora
 Linux version 4.18.16-300.fc29.x86_64

# Issue

## Failure
From ./test-suite.log:
...
FAIL: lib/logproto/tests/test_logproto
....
free(): double free detected in tcache 2

From valgrind test result:

==15149== Memcheck, a memory error detector
==15149== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15149== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==15149== Command: ./lib/logproto/tests/test_logproto
==15149==
==15152== Memcheck, a memory error detector
==15152== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15152== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==15152== Command:<path>/syslog-ng_fedora/build/lib/logproto/tests/test_logproto
==15152==
[2019-03-27T18:12:39.281019] Plugin module not found in 'module-path'; module-path='(null)', module='syslogformat'
==15152== Invalid free() / delete / delete[] / realloc()
==15152==    at 0x4839A0C: free (vg_replace_malloc.c:540)
==15152==    by 0x4EEBED1: g_free (in /usr/lib64/libglib-2.0.so.0.5800.3)
==15152==    by 0x4A6A78D: log_proto_server_options_destroy (logproto-server.c:191)
==15152==    by 0x40E989: deinit_proto_tests (proto_lib.c:174)
==15152==    by 0x408623: teardown (test_logproto.c:46)
==15152==    by 0x487232F: criterion_internal_test_teardown (in /usr/lib/libcriterion.so.3.1.0)
==15152==    by 0x408643: log_proto_test_base_jmp (test_logproto.c:50)
==15152==    by 0x4870800: run_test_child (in /usr/lib/libcriterion.so.3.1.0)
==15152==    by 0x48BFE2D: bxfi_main (in /usr/lib/libcriterion.so.3.1.0)
==15152==    by 0x5076412: (below main) (in /usr/lib64/libc-2.28.so)
==15152==  Address 0x527b9c0 is 0 bytes inside a block of size 6 free'd
==15152==    at 0x4839A0C: free (vg_replace_malloc.c:540)
==15152==    by 0x4EEBED1: g_free (in /usr/lib64/libglib-2.0.so.0.5800.3)
==15152==    by 0x4A6A78D: log_proto_server_options_destroy (logproto-server.c:191)
==15152==    by 0x408954: log_proto_test_base_impl (test_logproto.c:74)
==15152==    by 0x48721D1: criterion_internal_test_main (in /usr/lib/libcriterion.so.3.1.0)
==15152==    by 0x40863E: log_proto_test_base_jmp (test_logproto.c:50)
==15152==    by 0x4870800: run_test_child (in /usr/lib/libcriterion.so.3.1.0)
==15152==    by 0x48BFE2D: bxfi_main (in /usr/lib/libcriterion.so.3.1.0)
==15152==    by 0x5076412: (below main) (in /usr/lib64/libc-2.28.so)
...

## Steps to reproduce
./autogen.sh
mkdir build && cd build
../configure --enable-debug --enable-all-modules --enable-extra-warnings --prefix=$HOME/install/syslog-ng
make
make check

valgrind --trace-children=yes lib/logproto/tests/test_logproto

### PR DESCRIPTION
**Pull request by sudormrfstar**
Resolves #2658

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by sudormrfstar** [comment]
I did not run `make style-format` before I submitted the PR. I just realized there are a lot differences in terms of formatting including tab space number. Shall I re-submit?

**Comment by MrAnno** [comment]
You can force-push your branch with the corrections, the PR will be updated automatically.

**Comment by MrAnno** [comment]
Please use the following commit message pattern:
```
modulename: short description of the commit

summary

Signed-off-by: Full Name <email>
```

For example:
```
logproto: fix double-free error in logproto unit tests

Signed-off-by: Full Name <email>
```

File: lib/logproto/tests/test-regexp-multiline-server.c [hunk 1]
```diff
@@ -58,14 +63,22 @@ test_lines_separated_with_prefix(LogTransportMockConstructor log_transport_mock_
...
-  test_lines_separated_with_prefix(log_transport_mock_records_new);
+ParameterizedTestParameters(log_proto, test_lines_separated_with_prefix) {
+	static LogTransportMockConstructorParam log_transport_mock_new_data_list[] = {
+		log_transport_mock_stream_new,
+		log_transport_mock_records_new,
+	};
+
+	return cr_make_param_array(
+			LogTransportMockConstructorParam,
+			log_transport_mock_new_data_list, sizeof (log_transport_mock_new_data_list) / sizeof (log_transport_mock_new_data_list[0]));
```
Comment (MrAnno) [inline lib/logproto/tests/test-regexp-multiline-server.c]: You can use `G_N_ELEMENTS(log_transport_mock_new_data_list)` to calculate the size.

https://developer.gnome.org/glib/stable/glib-Standard-Macros.html#G-N-ELEMENTS:CAPS

File: lib/logproto/tests/test-regexp-multiline-server.c [hunk 2]
```diff
@@ -58,14 +63,22 @@ test_lines_separated_with_prefix(LogTransportMockConstructor log_transport_mock_
...
+}
+
+ParameterizedTest(LogTransportMockConstructorParam *param, log_proto, test_lines_separated_with_prefix) {
+	test_lines_separated_with_prefix(param->log_transport_mock_new);
```
Comment (MrAnno) [inline lib/logproto/tests/test-regexp-multiline-server.c]: `test_lines_separated_with_prefix()` is the actual test case here, you can remove the function call and insert the function's body instead.

The same applies to all other parameterized test cases.

File: lib/logproto/tests/test-server-options.c [hunk 3]
```diff
@@ -40,7 +40,6 @@ Test(log_proto, test_log_proto_server_options_limits)
                "LogProtoServerOptions.init_buffer_size is not initialized properly, init_buffer_size=%d", opts.init_buffer_size);
   cr_assert_gt(opts.max_buffer_size, 0,
                "LogProtoServerOptions.max_buffer_size is not initialized properly, max_buffer_size=%d", opts.max_buffer_size);
-  log_proto_server_options_destroy(&opts);
```
Comment (MrAnno) [inline lib/logproto/tests/test-server-options.c]: `opts` is local, this is not freed by the `teardown()` function, so the `destroy()` call should not be removed.

This same is true for the other 2 occurrences.

File: lib/logproto/tests/test-regexp-multiline-server.c [hunk 4]
```diff
@@ -29,6 +29,11 @@
 #include "logproto/logproto-regexp-multiline-server.h"
 
 #include <criterion/criterion.h>
+#include <criterion/parameterized.h>
+
+typedef struct LogTransportMockConstructor {
+	LogTransportMockConstructor log_transport_mock_new;
+} LogTransportMockConstructorParam;
```
Comment (MrAnno) [inline lib/logproto/tests/test-regexp-multiline-server.c]: This struct is not necessary, you can use `LogTransportMockConstructor` instead of `LogTransportMockConstructorParam`.

You've also redefined the name `LogTransportMockConstructor` (`struct LogTransportMockConstructor`), that is why Travis fails to compile the test:

https://travis-ci.org/balabit/syslog-ng/jobs/516846404#L2259

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: lib/logproto/tests/test-regexp-multiline-server.c [hunk 5]
```diff
@@ -212,12 +252,5 @@ test_first_line_without_prefix(LogTransportMockConstructor log_transport_mock_ne
   assert_proto_server_fetch(proto, "Foo Multiline\nmulti", -1);
 
   log_proto_server_free(proto);
-  log_proto_server_options_destroy(&proto_server_options);
```
Comment (Kokan) [inline lib/logproto/tests/test-regexp-multiline-server.c]: For both reviewing and later (for example bisect) it is better to split up changes that are independent.
The fix of double free and change in the test could have been a separate commit.

Comment (sudormrfstar) [reply lib/logproto/tests/test-regexp-multiline-server.c]: Thanks a lot for the comment. I will do it this way in the future for cases like this. Really good to know those best practices. Appreciated!
