### PR TITLE
Minor add-contextual-data fixes

### LINKED ISSUE #1179: add_contextual_data() - database.csv parsing issues
I have found some issues while tested database.csv file for add_contextual_data() parser with possible rfc4180 inputs.
RFC 4180 reference: [https://tools.ietf.org/html/rfc4180#section-2]

I have used the following general syslog-ng configuration files:

[syslog-ng.conf]

```
@version: 3.8
options { keep_hostname(yes); };
source s_file { file("/tmp/input.log"); };
parser p_acd { add_contextual_data(database(/tmp/database.csv) selector("${HOST}"));};
destination d_file { file("/tmp/output.log" template("$(format-json --scope dot-nv-pairs)\n")); };
destination d_file2 { file("/tmp/output2.log" template(".bbb: ${.bbb}, .eee: ${.eee}\n") ); };
log { source(s_file); parser(p_acd); destination(d_file); destination(d_file2); flags(flow-control); };
```

[input.log]

```
<38>Feb 25 14:09:07 10.10.10.10 testapp: test message

```

**Found issue 1**
  * CR not stripped from line endings

[database.csv] - with CRLF line endings on both lines

```
10.10.10.10,.bbb,ccc
10.10.10.10,.eee,fff
```

[syslog-ng console log] - CR (\r) not stripped, only LF (\n)

```
Outgoing message; message='.bbb: ccc\x0d, .eee: fff\x0d\x0a'
Outgoing message; message='{"_eee":"fff\r","_bbb":"ccc\r"}\x0a'
```

[output2.log]
```
.bbb: ccc
, .eee: fff
```
expected output would be:

```
Outgoing message; message='{"_eee":"fff","_bbb":"ccc"}\x0a'
```

**Found issue 2** 
  * Fields containing line breaks (CRLF) not allowed
  * syslog-ng did not start with the following database.csv file
  * expected behavior: syslog-ng can start

[database.csv]

```
"10.10.10.10",".b
bb","cc c"
```

[syslog-ng console error]

```
[2016-08-23T16:30:52.128575] Error while parsing add_contextual_data database;
[2016-08-23T16:30:52.128607] Failed to load the database file.;
```

**Found issue 3**
   * Escaped double-quotes added other double-quote at the end of the field

[database.csv]

```
"10.10.10.10",".bbb","c""cc"
```

[syslog-ng.conf]

```
@version: 3.8
options { keep_hostname(yes); };
source s_file { file("/tmp/input.log"); };
parser p_acd { add_contextual_data(database(/tmp/database.csv) selector("${HOST}"));};
destination d_file { file("/tmp/output.log" template("$(format-json --scope dot-nv-pairs)\n")); };
destination d_file2 { file("/tmp/output2.log" template(".bbb: ${.bbb}\n") ); };
log { source(s_file); parser(p_acd); destination(d_file); destination(d_file2); flags(flow-control); };
```

[syslog-ng console output]

```
[2016-08-23T16:40:02.275031] Outgoing message; message='.bbb: c"cc"\x0d\x0a'
[2016-08-23T16:40:02.275180] Outgoing message; message='{"_bbb":"c\"cc\"\r"}\x0a'
```

[output2.log] 

```
.bbb: c"cc"
```

expected output:

```
.bbb: c"cc
```

**syslog-ng version**:
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision: 3.8.1-1

### PR DESCRIPTION
**Pull request by MrAnno**
This PR
- adds CRLF line ending support to add-contextual-data
- sets the dialect of `CSVScanner` to [escape-double-char](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#reference-parsers-csv) in `ContextualDataRecordScanner` (as recorded in [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt))

Fixes #1179 (Issue 1 and 3)

---
This change is [Reviewable](https://reviewable.io/reviews/balabit/syslog-ng/1184)

### CODE REVIEW

File: modules/add-contextual-data/context-info-db.c [hunk 1]
```diff
@@ -260,19 +260,37 @@ context_info_db_get_selectors(ContextInfoDB *self)
   return g_hash_table_get_keys(self->index);
 }
 
+static void
+_truncate_eol(gchar *line, gsize line_len)
+{
+  if (line[line_len - 2] == '\r')
+    line[line_len - 2] = '\0';
+  else if (line[line_len - 1] == '\n')
+    line[line_len - 1] = '\0';
```
Comment (bkil-syslogng) [inline modules/add-contextual-data/context-info-db.c]: * what happens when `line_len < 2`?
* what happens when this is a last line in a file without a new line and it contains a stray `'\r'`, for example `"xy\rz"`?
* although it is unused as of now, I'd probably adjust `line_buf_len` as well

File: modules/add-contextual-data/tests/test_context_info_db.c [hunk 2]
```diff
@@ -267,6 +289,34 @@ test_import_with_valid_csv(void)
...
+  gchar csv_content[] = "selector1,name1,value1\r\n"
+                        "selector1,name1.1,value1.1";
+
+  TestNVPair expected_nvpairs_selector1[2] =
+  {
+    {.name = "name1",.value = "value1"},
+    {.name = "name1.1",.value = "value1.1"},
+  };
+
+  _assert_import_csv_with_single_selector(csv_content, "selector1", expected_nvpairs_selector1, 2);
```
Comment (bkil-syslogng) [inline modules/add-contextual-data/tests/test_context_info_db.c]: Manually passing the length of such an array is error prone.

File: modules/add-contextual-data/tests/test_context_info_db.c [hunk 3]
```diff
@@ -267,6 +289,34 @@ test_import_with_valid_csv(void)
 }
 
 static void
+test_import_with_valid_csv_crlf(void)
+{
+  gchar csv_content[] = "selector1,name1,value1\r\n"
```
Comment (bkil-syslogng) [inline modules/add-contextual-data/tests/test_context_info_db.c]: These could be `const`

Comment (MrAnno) [inline modules/add-contextual-data/tests/test_context_info_db.c]: `fmemopen()` needs a non-const buffer in `_assert_import_csv_with_single_selector`.

File: modules/add-contextual-data/tests/test_context_info_db.c (hunk 2 above)
Comment (MrAnno) [inline modules/add-contextual-data/tests/test_context_info_db.c]: I'll rewrite it to a "null-terminated" form, thanks.

File: modules/add-contextual-data/context-info-db.c (hunk 1 above)
Comment (MrAnno) [inline modules/add-contextual-data/context-info-db.c]: Wow, it was really thoughtless of me. Thanks.

Comment (bkil-syslogng) [inline modules/add-contextual-data/context-info-db.c]: Happens.

And I take the third point back. `line_buf_len` is good as is - `realloc()` took care of it. Though it might be useful to return `line_len` as well if we started supporting binary data later on or started optimizing away `strlen()'s`, that's what I tried to refer to. Binary data may not be that useful for a CSV, but other input forms might support that better.

File: modules/add-contextual-data/tests/test_context_info_db.c (hunk 2 above)
Comment (bkil-syslogng) [inline modules/add-contextual-data/tests/test_context_info_db.c]: I didn't specifically ask you to change it, because it kind of works correctly at present. In the null-terminated form, the null terminator could also be sometimes forgotten about. Although it would potentially be caught later on in case garbage resides after the array, there is no guarantee here.

I don't have a clear cut solution I could recommend, but you probably already know about clean magical macro workarounds like this:
https://github.com/balabit/syslog-ng/blob/c0bee2a8c5164f6968d2b6e2c3f4a4c0d8d9d0cd/modules/kvformat/tests/test_kv_scanner.c#L126

A much less hygienic workaround would be to introduce a macro that simply constructs `array, sizeof(array)/sizeof(array[0])`, and paste that instead of the argument.

File: modules/add-contextual-data/tests/test_context_info_db.c [hunk 4]
```diff
@@ -224,39 +247,65 @@ Test(add_contextual_data, test_import_with_valid_csv)
             "The context_info_db_is_indexed reports False after successful import&load operations.");
   fclose(fp);
 
-  TestNVPair expected_nvpairs_selector1[2] =
+  TestNVPair expected_nvpairs_selector1[] =
```
Comment (kvch) [inline modules/add-contextual-data/tests/test_context_info_db.c]: Could you provide more descriptive names for the test cases?

Comment (MrAnno) [inline modules/add-contextual-data/tests/test_context_info_db.c]: Of course.

**Comment by bkil-syslogng** [comment]
:+1: Please squash the fixup and rebase to master, otherwise seems okay.

**Comment by MrAnno** [comment]
squashed, rebased to master

File: modules/add-contextual-data/tests/test_context_info_db.c (hunk 4 above)
Comment (kvch) [inline modules/add-contextual-data/tests/test_context_info_db.c]: I meant these 3 TestNVPairs. :)

Comment (bkil-syslogng) [inline modules/add-contextual-data/tests/test_context_info_db.c]: @kvch What names did you have in mind?

Comment (MrAnno) [inline modules/add-contextual-data/tests/test_context_info_db.c]: @kvch Sorry, I thought you asked me to change the names of my _own_ tests.

These three `TestNVPair`s are introduced in 141fcb0b769092d9fab04ce2b7cd0a1b164533c8. I don't think that these should be changed since they contain meaningless values and are used exactly to test `selector1`, `selector2` and `selector3`.

Nevertheless, feel free to make a suggestion.

File: modules/add-contextual-data/tests/test_context_info_db.c [hunk 5]
```diff
@@ -194,15 +195,15 @@ Test(add_contextual_data, test_inserted_nv_pairs)
   ContextInfoDB *context_info_db = context_info_db_new();
   _fill_context_info_db(context_info_db, "selector", "name", "value", 1, 3);
 
-  TestNVPair expected_nvpairs[3] =
+  TestNVPair expected_nvpairs[] =
```
Comment (lbudai) [inline modules/add-contextual-data/tests/test_context_info_db.c]: Using 'hard-coded' values in the testcase was intentional.
I don't mind it, but I don't think this makes much more readable the code: in an assert I prefer concrete values instead of computed values.
