### PR TITLE
Preprocess-into error handling

### LINKED ISSUE #2720: syslog-ng silently fails if it can't open the destination file of --preprocess-into
## Version of syslog-ng

PE 7.0.14, but the latest OSE should be affected as well

## Platform

RHEL 7.5

# Issue

syslog-ng silently fails if it can't open the destination file of --preprocess-into

## Failure

When I was trying to print the preprocessed config to a file, I was wondering why the destination file was not created in the desired directory, when syslog-ng did not report any problems.

```
# strace /opt/syslog-ng/sbin/syslog-ng --preprocess-into=/root/EEE.conf
...
access("/opt/syslog-ng/lib/syslog-ng/libaffile.so", F_OK) = 0
stat("/opt/syslog-ng/lib/syslog-ng/libaffile.so", {st_mode=S_IFREG|0755, st_size=137750, ...}) = 0
stat("/opt/syslog-ng/lib/syslog-ng/libaffile.so", {st_mode=S_IFREG|0755, st_size=137750, ...}) = 0
open("/opt/syslog-ng/lib/syslog-ng/libaffile.so", O_RDONLY|O_CLOEXEC) = 11
read(11, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220\224\0\0\0\0\0\0"..., 832) = 832
fstat(11, {st_mode=S_IFREG|0755, st_size=137750, ...}) = 0
mmap(NULL, 2213152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 11, 0) = 0x7fecbccc5000
mprotect(0x7fecbccdf000, 2097152, PROT_NONE) = 0
mmap(0x7fecbcedf000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 11, 0x1a000) = 0x7fecbcedf000
mmap(0x7fecbcee1000, 1312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fecbcee1000
close(11)                               = 0
write(2, "[2019-05-09T16:53:07.887002] Mod"..., 89[2019-05-09T16:53:07.887002] Module loaded and initialized successfully; module='affile'
) = 89
read(10, "", 4096)                      = 0
ioctl(10, TCGETS, 0x7fff3f7147d0)       = -1 ENOTTY (Inappropriate ioctl for device)
close(10)                               = 0
munmap(0x7fecc405a000, 4096)            = 0
open("/root/EEE.conf", O_RDWR|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
exit_group(0)                           = ?
+++ exited with 0 +++
# /opt/syslog-ng/sbin/syslog-ng  --preprocess-into=/root/EEE.conf 
# ls -l EEE.conf
ls: EEE.conf nem érhető el: Nincs ilyen fájl vagy könyvtár
# pwd
/root
#
```

### PR DESCRIPTION
**Pull request by gaborznagy**
Handle file open errors in case of --preprocess-into is used.

Fixes #2720.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: lib/cfg.c [hunk 1]
```diff
@@ -547,7 +551,7 @@ _load_file_into_string(const gchar *fname)
 }
 
 gboolean
-cfg_read_config(GlobalConfig *self, const gchar *fname, gboolean syntax_only, gchar *preprocess_into)
```
Comment (szemere) [inline lib/cfg.c]: Nice catch!
