### PR TITLE
amqp configurable max connection and frame size

### LINKED ISSUE #2340: Syslog-ng AMQP cannot connect to RabbitMQ 3.7.5 due to channel_max = 0
## Version of syslog-ng
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision: 3.5.6-2+b1 [@416d315] (Debian/unstable)
Compile-Date: Oct  1 2014 18:23:11
Available-Modules: dbparser,afsocket-notls,confgen,afstomp,redis,csvparser,affile,afmongodb,afsocket-tls,afsocket,afprog,system-source,afsql,linux-kmsg-format,syslogformat,afsmtp,afamqp,tfgeoip,afuser,json-plugin,basicfuncs,cryptofuncs
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on

## Platform
Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie

# Issue
Syslog-ng cannot connect to a RabbitMQ AMQP destination when that destination is running RabbitMQ version 3.7.5.

Note:
1. The version of RabbitMQ that it cannot connect to is running rabbit version 3.7.5.
2. The same syslog-ng instance works perfectly when connected to an older rabbit server running rabbit version 3.5.7.
3. I don't know what libraries Syslog-ng uses behind the scenes, but the same problem has been found and fixed in rabbitmq-c here:
https://github.com/alanxz/rabbitmq-c/issues/513

Syslog-ng error log:
```
Module loaded and initialized successfully; module='syslogformat'
Initializing AMQP destination; vhost='/', host='test-rabbit.server', port='5672', exchange='ncsalog', exchange_type='topic'
Worker thread started; driver='d_rabbit#0'
Running application hooks; hook='1'
Running application hooks; hook='3'
syslog-ng starting up; version='3.5.6'
Error during AMQP login; driver='d_rabbit#0', error='Connection reset by peer', time_reopen='60'
```

RabbitMQ error log:
```
{handshake_error,tuning,0,{exit,{amqp_error,not_allowed,"negotiated channel_max = 0 is higher than the maximum allowed value (2047)",'connection.tune'},'connection.tune_ok',[{rabbit_misc,protocol_error,1,[{file,"src/rabbit_misc.erl"},{line,304}]},{rabbit_reader,handle_method0,2,[{file,"src/rabbit_reader.erl"},{line,1147}]},{rabbit_reader,handle_method0,3,[{file,"src/rabbit_reader.erl"},{line,1100}]},{rabbit_reader,handle_input,3,[{file,"src/rabbit_reader.erl"},{line,1015}]},{rabbit_reader,recvloop,4,[{file,"src/rabbit_reader.erl"},{line,461}]},{rabbit_reader,run,1,[{file,"src/rabbit_reader.erl"},{line,443}]},{rabbit_reader,start_connection,4,[{file,"src/rabbit_reader.erl"},{line,362}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}
```

## Steps to reproduce

syslog-ng -Fevd

## Configuration

```
-- snip --
destination d_rabbit {
    amqp(
        vhost("/")
        host("test-rabbit.server")
        port(5672)
        username("admin")
        password("adminpass")
        exchange("ncsalog")
        exchange-type("topic")
        persistent(yes)
        body("$(format-json Environment=dev Application=$PROGRAM Level=$LEVEL message=$MESSAGE host=$FULLHOST Request_IP=${NCSA.REQUEST_IP} User_Identifier=${NCSA.USER_IDENTIFIER} User_Id=${NCSA.USER_ID} Log_Timestamp=${NCSA.TIMESTAMP} $
    );
};
-- snip --
```

### PR DESCRIPTION
**Pull request by Kokan**
It makes possible to configure the `max_channel` and `frame_size` for amqp destination. Also relays on a default value supplied by rabbitmq project.

Fixes #2340

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: modules/afamqp/afamqp-parser.c [hunk 1]
```diff
@@ -42,6 +42,8 @@ static CfgLexerKeyword afamqp_keywords[] =
   { "persistent",   KW_PERSISTENT },
   { "username",     KW_USERNAME },
   { "password",     KW_PASSWORD },
+  { "max_channel",     KW_MAX_CHANNEL },
```
Comment (lbudai) [inline modules/afamqp/afamqp-parser.c]: just a nitpick : I know that this indentation "style" is part of the original implementation, so nothing to do here from your part, but when I saw the indentation patch.... well I just hoped that this ugly formatting has been also covered by that patch :)

Comment (Kokan) [reply modules/afamqp/afamqp-parser.c]: Yeah, I should have. But those refactor/indent style change I just cherry picked from my other work in progress afamqp branch, because I do not not if that other branch is going to become a PR or not.
