### PR TITLE
file: avoid change file permission if file is device

### LINKED ISSUE #383: Please do not chown/chmod if the log file is a device like e.g. /dev/null
Please suppress the chown/chmod on the log file if the destination file is a device like e.g. `/dev/null`, i.e. any path starting with `/dev/`.

Changing the permissions of `/dev/null` unexpectedly is known to cause the weirdest issues as e.g. shell scripts running under a non-root user will fail upon redirection to `/dev/null`, etc.

(Yes, I know doing so isn't the best idea, but someone may try it just for an experiment, reverts it soon afterwards, but the damage is done already. And maybe the administrator doesn't even relate the new issues caused by this with his little experiment, because he already reverted that change -- which does't revert the permission changes on `/dev/null`.)

For completeness: I experienced this behaviour on Debian 7 Wheezy (current Debian Stable Release) which ships syslog-ng 3.3.5.

### PR DESCRIPTION
**Pull request by deirf**
It could be changed only if the file (source or destination) is not
a device because all devices are system entity in filesystem. 
Fixes #383 

Signed-off-by: Fried Zoltan <zoltan.fried@balabit.com>

### CODE REVIEW

File: lib/file-perms.h [hunk 1]
```diff
@@ -51,5 +51,6 @@ gboolean file_perm_options_apply_file(const FilePermOptions *self, gchar *name);
 gboolean file_perm_options_apply_dir(const FilePermOptions *self, gchar *name);
 gboolean file_perm_options_apply_fd(const FilePermOptions *self, gint fd);
 gboolean file_perm_options_create_containing_directory(const FilePermOptions *self, gchar *name);
+gboolean file_perm_options_check_file_is_device(gchar *name);
```
Comment (lbudai) [inline lib/file-perms.h]: Please, use `const gchar *` as type for `name`. (name is used only for passing it to `stat` and `stat` expects `const char *`).

**Comment by lbudai** [comment]
If you add a `fixes #383` to your commit message, github will close automatically the related bug after it is merged.

File: lib/file-perms.c [hunk 2]
```diff
@@ -119,6 +119,17 @@ file_perm_options_init(FilePermOptions *self, GlobalConfig *cfg)
 }
 
 gboolean
+file_perm_options_check_file_is_device(const gchar *name)
+{
+  struct stat st;
+
+  if (stat(name, &st) >= 0)
```
Comment (lbudai) [inline lib/file-perms.c]: I suggest to you use `lstat` in order to handle correctly the symlinked device files.

File: lib/file-perms.h [hunk 3]
```diff
@@ -51,5 +51,6 @@ gboolean file_perm_options_apply_file(const FilePermOptions *self, gchar *name);
 gboolean file_perm_options_apply_dir(const FilePermOptions *self, gchar *name);
 gboolean file_perm_options_apply_fd(const FilePermOptions *self, gint fd);
 gboolean file_perm_options_create_containing_directory(const FilePermOptions *self, gchar *name);
+gboolean file_perm_options_check_file_is_device(const gchar *name);
```
Comment (lbudai) [inline lib/file-perms.h]: hmm... are you sure that this is the right place for this function?
I mean `check_file_is_device` is independent from `FilePermOptions`.
(If FilePermOptions is a class, then this function is not a method of that class...)

**Comment by lbudai** [comment]
hint: we have the `lib\pathutils.{h,c}` for these kind of functions ;-)
and I would rename it to `is_file_device` (maybe we can use g_file_test() based solution...)

File: lib/file-perms.c (hunk 2 above)
Comment (deirf) [inline lib/file-perms.c]: OK. It is possile :)

**Comment by deirf** [comment]
Thanks, I did not know the pathutils files. But g_file_test() can not check devices

**Comment by deirf** [comment]
Yes, it is possible open a device as a socket, but the result will be interesting I think :) 
The main reason is that the syslog-ng can be configured in the same way.

**Comment by deirf** [comment]
It is difficult to solve to avoid open an non unix socket as unix socket because of layer violation.This PR print only a warning message at this moment and do not change the file permission.

**Comment by gregory094** [comment]
`lstat` should be changed to `stat`

**Comment by deirf** [comment]
@lbudai could you look at this PR?

**Comment by lbudai** [comment]
I was wrong: not _before_  but after `afsocket_sd_init()` and before setting the permission.

**Comment by deirf** [comment]
@lbudai: Yes, it better sollution. I modified it.

File: modules/afsocket/afunix-source.c [hunk 4]
```diff
@@ -85,9 +86,20 @@ static gboolean
...
+  result = afsocket_sd_init_method(s);
+  
+  if (is_file_socket(self->filename))
+    afunix_sd_apply_perms_to_socket(self);
+  else
+    {
+      msg_warning("Source is not a unix socket",
+                evt_tag_str("filename", self->filename),
+                NULL);
+    }
```
Comment (lbudai) [inline modules/afsocket/afunix-source.c]: Hmmm... this is not the best.
What if `afsocket_sd_init_method()` fails? We should return immediately.
And a code-style issue:
when using a block statement as one of the branches within an `if-else` statment, then every branch should be grouped into a block-statement, even if it contains only one statement.

Comment (deirf) [inline modules/afsocket/afunix-source.c]: Yes, You all right. It is fixed. Thanks a lot !

File: modules/afsocket/afunix-source.c [hunk 5]
```diff
@@ -85,9 +86,22 @@ static gboolean
...
+  
+  if (is_file_socket(self->filename))
+    {
+      afunix_sd_apply_perms_to_socket(self);
+    }
+  else
+    {
+      msg_warning("Source is not a unix socket",
+                evt_tag_str("filename", self->filename),
+                NULL);
```
Comment (lbudai) [inline modules/afsocket/afunix-source.c]: The previous version returned with FALSE when the file was not a socket...
Why did you change it?

File: modules/afsocket/afunix-source.c [hunk 6]
```diff
@@ -85,9 +86,22 @@ static gboolean
 afunix_sd_init(LogPipe *s)
 {
   AFUnixSourceDriver *self = (AFUnixSourceDriver *) s;
+ 
+  if (!afsocket_sd_init_method(s))
+    return FALSE
+
```
Comment (lbudai) [inline modules/afsocket/afunix-source.c]: A missing `;` ... this is why Travis has failed.

File: modules/afsocket/afunix-source.c [hunk 7]
```diff
@@ -85,6 +86,14 @@ static gboolean
...
 {
   AFUnixSourceDriver *self = (AFUnixSourceDriver *) s;
+ 
+  if (!is_file_socket(self->filename))
+    {
+      msg_warning("Source is not a unix socket",
+                evt_tag_str("filename", self->filename),
+                NULL);
+      return FALSE;
+    }
```
Comment (deirf) [inline modules/afsocket/afunix-source.c]: File socket checking before `afsocket_sd_init_method` is must because `afsocket_sd_init_method` will be false if file is not a socket and syslog-ng is writting only the `Address already in use ...` error message.

File: modules/afsocket/afunix-source.c [hunk 8]
```diff
@@ -86,6 +87,14 @@ afunix_sd_init(LogPipe *s)
 {
   AFUnixSourceDriver *self = (AFUnixSourceDriver *) s;
 
+  if (!is_file_socket(self->filename))
```
Comment (deirf) [inline modules/afsocket/afunix-source.c]: File socket checking before `afsocket_sd_init_method` is must because `afsocket_sd_init_method` will be false if file is not any type of socket and syslog-ng is writting out only the `Address already in use` ... error message.

File: lib/pathutils.c [hunk 9]
```diff
@@ -36,3 +37,25 @@ is_file_regular(const char *filename)
...
+
+gboolean
+is_file_socket(const gchar *name)
+{
+  struct stat st;
+
+  if (stat(name, &st) >= 0)
+    return S_ISSOCK(st.st_mode);
+  else
+    return TRUE;
```
Comment (deirf) [inline lib/pathutils.c]: The `return TRUE` is mandatory because it is valid scenario if the socket is not exist.

**Comment by lbudai** [comment]
Hmm... we should talk about it IRL.
I think this is not mergeable.

File: modules/afsocket/afunix-source.c [hunk 10]
```diff
@@ -86,6 +87,14 @@ afunix_sd_init(LogPipe *s)
...
   AFUnixSourceDriver *self = (AFUnixSourceDriver *) s;
 
+  if (is_file_socket(self->filename) == PU_FILE_TEST_FALSE)
+    {
+      msg_warning("Source is not a unix socket",
+                evt_tag_str("filename", self->filename),
+                NULL);
+      return FALSE;
+    }
+
```
Comment (lbudai) [inline modules/afsocket/afunix-source.c]: `bind()` is called during `afsocket_sd_init_method()` and this means that if `is_file_socket()` returns true, 
then the `bind()` with fail with EADDRINUSE

This is why I ask you to call this check _after_ the init method.

**Comment by deirf** [comment]
afsocket_sd_init() will return FALSE if socket is not device.
afsocket_sd_init() will return TRUE if socket is device or socket does not exist before bind.
This reason afunix_sd_apply_perms_to_socket() function will be run if socket is device or socket does not exist before bind.
