### PR TITLE
Fix journald program name flapping

### LINKED ISSUE #831: flapping ${PROGRAM} using systemd
I noticed an odd flapping behaviour on one of our servers:

* using `logger -t test` the name of the program changes from one invocation to the other
* `journalctl` always reports the right value (`PROGRAM=test`)
* `messages` (syslog-ng) randomly flaps between `test` and `logger`

```
☠ rpm -q syslog-ng
syslog-ng-3.7.2-2.el7.centos.x86_64
☠ sh /tmp/system-expand
## system() expands to:

channel {
    source {
systemd-journal();
    }; # source
channel {
  channel {
    parser {
      json-parser(prefix('.cim.') marker('@cim:'));
    }};
    flags(final);
  };
  channel { };
};
}; # channel
;
☠ tail -n0 -F /var/log/messages&
☠ logger -t test test
☠ Dec 10 15:38:11 node01 logger[29418]: test
logger -t test test
☠ Dec 10 15:38:14 node01 logger[29420]: test
logger -t test test
☠ Dec 10 15:38:16 node01 test[29421]: test
logger -t test test
☠ Dec 10 15:38:17 node01 logger[29422]: test

☠ journalctl | tail -n4
Dec 10 15:38:11 node01 test[29418]: test
Dec 10 15:38:14 node01 test[29420]: test
Dec 10 15:38:16 node01 test[29421]: test
Dec 10 15:38:17 node01 test[29422]: test
```

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes #831 

The following changes are included in this PR:
* insert all the read key-value pairs under `.journald.`
* if we can map something to a syslog-ng macro, do it as we do it now (like `_HOSTNAME`)
* prefer `SYSLOG_IDENTIFIER` over `_COMM` for setting `PROGRAM`
* make these changes enabled only after `3.8`

After the changes I did some refactoring.

### CODE REVIEW

File: modules/systemd-journal/journal-reader.c [hunk 1]
```diff
@@ -149,14 +149,8 @@ __reader_wakeup(LogSource *s)
 }
 
 static void
-__handle_data(gchar *key, gchar *value, gpointer user_data)
+__map_key_value_pairs_to_syslog_macros(LogMessage *msg, gchar *key, gchar *value, gssize value_len)
 {
```
Comment (bazsi) [inline modules/systemd-journal/journal-reader.c]: single underscores is what we agreed upon.

File: modules/systemd-journal/journal-reader.c [hunk 2]
```diff
@@ -193,18 +174,50 @@ __handle_data(gchar *key, gchar *value, gpointer user_data)
...
+  __map_key_value_pairs_to_syslog_macros(msg, key, value, value_len);
+  __fill_message(options, msg, key, value, value_len);
+}
+
+static void
+__set_program(LogMessage *msg)
+{
+  gssize value_length = 0;
+  const gchar *value = log_msg_get_value_by_name(msg, "SYSLOG_IDENTIFIER", &value_length);
+
```
Comment (bazsi) [inline modules/systemd-journal/journal-reader.c]: this doesn't take prefix into account...

File: modules/systemd-journal/journal-reader.c [hunk 3]
```diff
@@ -597,6 +611,11 @@ journal_reader_options_init(JournalReaderOptions *options, GlobalConfig *cfg, co
   if (options->recv_time_zone_info == NULL)
     options->recv_time_zone_info = time_zone_info_new(options->recv_time_zone);
 
+  if (options->prefix == NULL && cfg_is_config_version_older(cfg, 0x0308))
+    {
+      options->prefix = g_strdup(".journald.");
```
Comment (bazsi) [inline modules/systemd-journal/journal-reader.c]: please issue an upgrade warning here.

File: modules/systemd-journal/journal-reader.c (hunk 2 above)
Comment (ihrwein) [inline modules/systemd-journal/journal-reader.c]: prefix is added by _fill_message().

I think the code is cleaner without the nvhandle-s. I would optimize it further when somebody reports back that it is much slower.

Comment (bazsi) [inline modules/systemd-journal/journal-reader.c]: but you are getting the value from the message at this point, so if it was
set as "${.prefix.SYSLOG_IDENTIFIER}", you won't get it here.




-- 
Bazsi

Comment (ihrwein) [inline modules/systemd-journal/journal-reader.c]: Now I see! You are right.

**Comment by ihrwein** [comment]
@juhaszviktor Could you check the failing testcase, please? (I debugged it but found nothing.)

File: modules/systemd-journal/journal-reader.c [hunk 4]
```diff
@@ -193,18 +174,66 @@ __handle_data(gchar *key, gchar *value, gpointer user_data)
...
-          g_free(prefixed_key);
-        }
+      gchar *prefixed_key = g_strdup_printf("%s%s", options->prefix, key);
+      log_msg_set_value_by_name(msg, prefixed_key, value, value_len);
+      g_free(prefixed_key);
+    }
+}
+
+static void
+__handle_data(gchar *key, gchar *value, gpointer user_data)
```
Comment (juhaszviktor) [inline modules/systemd-journal/journal-reader.c]: Please use single underscore

File: modules/systemd-journal/journal-reader.c [hunk 5]
```diff
@@ -234,6 +263,7 @@ __handle_message(JournalReader *self)
 
   journald_foreach_data(self->journal, __handle_data, args);
   __set_message_timestamp(self, msg);
```
Comment (juhaszviktor) [inline modules/systemd-journal/journal-reader.c]: I know, that the double underscores don't come from your pencil, but if you modify the file, please correct the underscores

**Comment by ihrwein** [comment]
Based on @juhaszviktor's suggestion I fixed the unit test. The branch is rebased, ready for review.

**Comment by bazsi** [comment]
This looks good to me, there are still some double underscores in the tests, and I see trivial optimizations in case this would be slow, but I think this can go in as it is now.

**Comment by ihrwein** [comment]
@juhaszviktor just a quick glance? :)

**Comment by bazsi** [comment]
I have submitted a pull request against your branch yesterday that contains a couple of fixes yet.

**Comment by bazsi** [comment]
This one: https://github.com/ihrwein/syslog-ng/pull/2

**Comment by ihrwein** [comment]
Thanks. I've merged Bazsi's changes into mine. Should I fixup the commits ?

**Comment by juhaszviktor** [comment]
:+1:

**Comment by ihrwein** [comment]
rebased to master, force pushed

**Comment by dnsjts** [comment]
:+1:

**Comment by czanik** [comment]
Could you backport this fix to 3.7? It would resolve https://bugzilla.suse.com/show_bug.cgi?id=987453

**Comment by phemmer** [comment]
I second the backport to 3.7. At the very least, the `SYSLOG_IDENTIFIER` shouldn't be stripped out. Otherwise I could do something like `rewrite r { set("${.journald.SYSLOG_IDENTIFIER}", value("PROGRAM")) }`. But `${.journald.SYSLOG_IDENTIFIER}` doesn't exist (other journald fields are added, just not this one).

**Comment by maxenced** [comment]
+1 for backport to 3.7 :)

**Comment by faxm0dem** [comment]
this is our workaround for the time being: use `logger -n localhost` which will use `network()` source  instead `system()`
