### PR TITLE
Fix reload race in msg macro + drop compatbility with syslog-ng < 3.0

### LINKED ISSUE #1423: Custom template for remote syslog temporarily ignored when HUP is received
# syslog-ng

Docker image balabit/syslog-ng:latest

## Version of syslog-ng

```
$ docker exec -it syslog-ng syslog-ng --version
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 3.9.1-2
Module-Directory: /usr/lib/syslog-ng/3.9
Module-Path: /usr/lib/syslog-ng/3.9
Available-Modules: confgen,csvparser,add-contextual-data,afprog,mod-java,affile,geoip-plugin,date,pseudofile,syslogformat,json-plugin,basicfuncs,afuser,linux-kmsg-format,afstomp,afamqp,afsocket,kvformat,cef,cryptofuncs,disk-buffer,graphite,afmongodb,dbparser,sdjournal,system-source
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
```

## Platform

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

# Issue

## Failure

In systems where newsyslog is used to rotate log files that are written to disk by syslog-ng, it has been observed that sometimes when the HUP signal (that is sent to syslog-ng process by newsyslog) causes wrong template to be used temporarily for a remote syslog server that has been configured to use a custom template.

I suspect that there is some kind of race-condition when reloading the configuration files.

It can be reproduced quite easily using docker, with a simple syslog server in python acting as remote (catching the wrong template), a python script that generates frequent logging and shell script that sends regular HUP signals.

The custom template is defined without the program name:
```
<$PRI>$DATE $HOST : $MSG
```

Sometimes when the HUP signal is received, this format is sent to the remote server:
```
<190>Apr 10 09:45:29 0c30188d28c5 : myapp: Writing some log data 0
```

Where the expected format is to follow the custom template:
```
<190>Apr 10 09:45:29 0c30188d28c5 : Writing some log data 0
```

## Steps to reproduce

1. Start syslog-ng using docker in one terminal
```
$ docker run -it -v "$PWD/syslog-ng.conf":/etc/syslog-ng/syslog-ng.conf -v $PWD:/mnt -p 1514:1514 --name syslog-ng balabit/syslog-ng:latest
```

2. Start the simple python syslog server acting as remote on the host (with the docker local IP as argument, don't forget modify syslog-ng.conf if different) in another terminal
```
$ python pysyslog-reproduction.py 172.17.0.1
```

3. Run the reproduction shell script inside the docker container on a third terminal
```
$ docker exec -it syslog-ng bash /mnt/run-reproduction.bash
```

4. Observe the second terminal and you should get a "FOUND WRONG TEMPLATE!!" printout which means that the issue is reproduced
```
$ python pysyslog-reproduction.py 172.17.0.1
<190>Apr 10 09:44:15 617265bae7d9 : Writing some log data 0
<190>Apr 10 09:44:18 617265bae7d9 : Writing some log data 100292
<190>Apr 10 09:44:21 617265bae7d9 : Writing some log data 200462


FOUND WRONG TEMPLATE!!
<190>Apr 10 09:44:21 617265bae7d9 : myapp: Writing some log data 213854
```

## Configuration

```
$ cat syslog-ng.conf
@version: 3.9

source src {
    unix-stream("/dev/log");
    internal();
};

filter f_myapp { program("^myapp$"); };

template t_mytemplate { template("<$PRI>$DATE $HOST : $MSG\n"); template_escape(no); };

destination d_myremote {
    udp("172.17.0.1"
        port(1514)
        template(t_mytemplate)
        frac_digits(0)
        suppress(5)
    );
};

log {
    source(src);
    filter(f_myapp);
    destination(d_myremote);
};

```

## Input and output logs (if possible)

No special or strange logging from syslog-ng observed has been when the issue happens.

Scripts and configuration to reproduce can be found at [this gist](https://gist.github.com/epontan/5699c07473c6210051ba7f00ca19e778)

### PR DESCRIPTION
**Pull request by bazsi**
This branch fixes #1423 as well as it drops the compatibility to syslog-ng versions below 3.0.

The bug itself manifests because of the compatibility support and fixing it is pretty complicated, as it would require propagating the GlobalConfig instance to a place where it isn't present.

Anyway, I felt it was time to drop support for syslog-ng config versions below 3.0, as 3.0 is roughly 9 years old anyway (released on 24th December 2008 as a christmas present :)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

File: lib/cfg-lexer.c [hunk 1]
```diff
@@ -935,18 +935,18 @@ cfg_lexer_lex(CfgLexer *self, YYSTYPE *yylval, YYLTYPE *yylloc)
...
 
       if (configuration->user_version == 0 && configuration->parsed_version == 0)
         {
-          /* no version selected yet, and we have a non-pragma token, this
-           * means that the configuration is meant for syslog-ng 2.1 */
-          msg_warning("WARNING: Configuration file has no version number, assuming syslog-ng 2.1 format. Please add @version: maj.min to the beginning of the file to indicate this explicitly");
-          cfg_set_version(configuration, 0x0201);
+          msg_error("ERROR: configuration files without a version number has become unsupported in " VERSION_3_13
+                    ", please specify a version number using @version and update your configuration accordingly");
+          return LL_ERROR;
```
Comment (lbudai) [inline lib/cfg-lexer.c]: Wouldn't be better if we fallback to the latest version (with a warning message) instead of returning with this error?

Comment (lbudai) [reply lib/cfg-lexer.c]: We talked about it IRL and we keep this as is.

Comment (alltilla) [reply lib/cfg-lexer.c]: Do you happen to remember the argument behind that?
Asking, because using the latest version might be a solution to #3068
