### PR TITLE
system-source: added exclude_kmsg option instead of container detection

### LINKED ISSUE #2156: system-source: Linux container detection is incorrect
# syslog-ng

## Version of syslog-ng

Current master, but the problem dates back to 2014, to the original implementation of `_is_running_in_linux_container()`.

## Platform

Debian GNU/Linux Stable, Ubuntu 16.04, likely a lot of others.

# Issue

The main issue is that when using the `system()` source, none of `/dev/kmsg` or `/proc/kmsg` gets added as sources, thus, we will be missing kernel messages.

## Steps to reproduce

1. Use the configuration shown below.
2. Make sure you're not running in a container.
3. Use the `system-expand.sh` tool, and verify that `kmsg` does not appear in the output.

## Configuration

```
@version: 3.16

source s_system { system(); };
```

## Input and output logs (if possible)

I'm not pasting the expanded source here, as that is easy to reproduce. However, I'm pasting `/proc/1/cgroup`:

```text
❯ cat /proc/1/cgroup
10:devices:/
9:cpuset:/
8:memory:/
7:freezer:/
6:blkio:/
5:pids:/
4:cpu,cpuacct:/
3:net_cls,net_prio:/
2:perf_event:/
1:name=systemd:/init.scope
0::/init.scope
```

If we look at [`_is_running_in_linux_container`](https://github.com/balabit/syslog-ng/blob/c9c3992e006414ce63add1f3854c13fb1d09cb20/modules/system-source/system-source.c#L230-L237), we see that it checks if all lines end with `/`. This might have been true back in 2014, but is not a correct check today, there are at least two lines that do not end like that, yet, we are definitely not running in a container.

## Thanks

The issue was noticed by `kcuf` on the IRC channel, who also provided the expanded `system()` source, which shed light on the underlying issue.

### PR DESCRIPTION
**Pull request by szemere**
system-source: removed container detection from system source,
because changes in kernel code made it unreliable. Since it was
only used for excluding kmsg logs, a new optional "exclude-kmsg()"
option was introduced to make the function user configurable.

Question: Where should we store the const string literal for the option?

Resolves #2156

### CODE REVIEW

File: modules/system-source/system-source.c [hunk 1]
```diff
@@ -216,46 +216,21 @@ system_sysblock_add_linux_kmsg(GString *sysblock)
...
-system_sysblock_add_linux(GString *sysblock)
+system_sysblock_add_linux(GString *sysblock, CfgArgs *args)
 {
   if (service_management_get_type() == SMT_SYSTEMD)
     system_sysblock_add_systemd_source(sysblock);
   else
     {
       system_sysblock_add_unix_dgram(sysblock, "/dev/log", NULL, "8192");
-      if (!_is_running_in_linux_container())
+      if (cfg_args_get(args, "exclude_kmsg") == NULL)
```
Comment (algernon) [inline modules/system-source/system-source.c]: This only checks that the option is present, and does not account for things like `exclude-kmsg(no)`. If we require the presence of the option only (which is a great idea, by the way!), we should either mandate that it has no arguments, or treat at least some falsey values as if the option wasn't present.

For simplicity's sake, I'd do something like this:

```c
if (cfg_args_contains(args, "exclude_kmsg")) {
  if (cfg_args_get(args, "exclude_kmsg")) {
    msg_error("system(): The exclude_kmsg() option takes no arguments.");
    return FALSE;
  }
  system_sysblock_add_linux_kmsg(sysblock);
}
```

This would require `system_sysblock_add_linux` to start returning `gboolean`, and the other branches should return `TRUE`. We'd also need to adjust `system_generate_system_transports` below to check the return value and do the right thing (`goto exit`).

We need two steps (`_contains` and `_get`), because we can't simply check if the value of the argument is empty, because that would be true even if the option wasn't present. So we first make sure it is present, and only THEN check the value.

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: modules/system-source/system-source.c (hunk 1 above)
Comment (szemere) [reply modules/system-source/system-source.c]: Thank You @algernon for taking time on this. I really like your idea, which adds more flexibility to the feature. First I was overwhelmed with the concept to not strict this settings any more than needed, just silently accept any value, so it can be expanded - without syntax modification - in the future.

In the meantime I discussed this question IRL with @mitzkia. To get some "best practice" from testers point of view.

New approach: introduce the **flags** keyword to the system source, and add **exclude-kmsg** as the first possible item.

**pros**
- **flags** is already a well known keyword, so it will align well with the current logic.
- It will represent the "present or not" nature of this option.

**cons**
- It will be a little bit confusing since the namespace will be different than: source drivers, syslog parser, log path's. (Flags are different for these items.)

note: We are trying to generalize a single option. It is very good to "try to think about the future", but I think it is almost impossible. So I will gladly accept any new opinion in the topic, and ready to implement the most popular one.

Comment (algernon) [reply modules/system-source/system-source.c]: While I like the `flags` idea too, in context of `system-source`, it isn't as simple to implement as `exclude-kmsg()` would have been, because it would need to break up the string into list items... on the other hand, since we only have one flag now, perhaps that's not needed, and a simple `strcmp(__normalize_key(flags), "exclude_kmsg")` would do?

In other words, I'll back the `flags(exclude-kmsg)` idea.

**Comment by furiel** [comment]
I would prefer a more mathematically strict approach: /dev/kmsg logs is part of the system logs by definition, so when user asks for system() logs, then syslog-ng should provide those as well. If a user says that they want system logs except /dev/kmsg, then they should not use the system source, but they can define their own source according to their needs and use that.

Giving specific enabling disabling options to a generalized solution can be a source of confusion, and hard to maintain. As an analog: let's say users wants to use default-network-drivers, but does not want to open rfc5424 ports. We would still not extend the api by making those ports switchable, other users might want to disable other parts of the collection. We would say that default-network-drivers does not fit their needs.

With all that said, I would prefer just deleting this container check, and provide all system logs unconditionally.

**Comment by algernon** [comment]
> I would prefer a more mathematically strict approach: /dev/kmsg logs is part of the system logs by definition, so when user asks for system() logs, then syslog-ng should provide those as well.

I disagree here: `/dev/kmsg` is part of the system logs on the host, but it is kinda pointless to collect it in the containers too. Not to mention that if we run on an older kernel which only has `/proc/kmsg` (shouldn't happen, but as long as we support `/proc/kmsg`, we should consider this case too) then containers reading from it will create a kind of a race (see #254): all readers will compete for the logs, and the fastest will win, resulting in the logs being scattered among the contained syslogds and the host's. That's not a healthy situation to have.

Now if we removed `/proc/kmsg` support too...

> they should not use the system source, but they can define their own source according to their needs and use that

But... `system-source()` adds quite a bit of functionality, that would be inconvenient to replicate in containers. It would also make it a lot of work to keep the kmsg-less copy up-to-date with any enhancements that come for the stock `system-source()`.

> ... `default-network-drivers` ...

Well, that has `default` in its name, `system-source()` does not. `default-network-driver` is also pure SCL, while `system-source` is a tad more complicated than that. To slightly change `default-network-drivers`, one only needs to copy the SCL and edit it. To do something similar to `system-source`, one either needs to copy the C module and compile it, or expand the source and copy that - neither of which is convenient, or practical.

**Comment by furiel** [comment]
Ok, I see why we need the switchability. Thanks for explaining.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
I think flags () is not very intuitive, and has been a bad pattern in the
past.

It's a pattern though, so there are pros and cons in using it. We started
to deviate from flags already in favor of yes/no options and that's what i
would use today.

**Comment by szemere** [comment]
Hello,
 adding another aspect to this way too long thread:

 With #1788 ALL system() source parameters are passed to the **app-parser-generator** which (according to [this](https://github.com/balabit/syslog-ng/blob/174261f4fc71752121d01af87b8c9f3f05c53781/modules/appmodel/app-parser-generator.c#L192)) will silently ignores all unknown arguments.

My question is: Which will be better?
- Starting to add arguments to the system source, with the implicit knowledge: they will be passed to the app-parser-generator, which will ignore them.
- During the process of "system source only" arguments in [system-source.c:system_generate_system_transports](https://github.com/balabit/syslog-ng/blob/174261f4fc71752121d01af87b8c9f3f05c53781/modules/system-source/system-source.c#L353) remove the "recognized" ones, so app-parser-generator will not get them.

IMHO both solution contains some layering violation, and disallow any **common** argument between the system source and app-parser-generator. (Either both of them will process it, or one of them will starve the other one.)

Br,
Laci

**Comment by bazsi** [comment]
I would do the second. Collisions of arguments between the two are
unlikely, and this seems more intuitive to me.

**Comment by kira-syslogng** [comment]
Build SUCCESS
