### PR TITLE
python: make init() optional for destinations

### LINKED ISSUE #1756: python: defining init method is mandatory, while deinit is not
Currently syslog-ng python module (edit: b̶o̶t̶h̶ destination a̶n̶d̶ ̶p̶a̶r̶s̶e̶r̶) forces users to define an init method, even though the deinit method is not mandatory. If the init method is missing, syslog-ng generates a
```
def init(self, options):
    return False
```
like method, thus syslog-ng fails to initialize. Syslog-ng should let users omit init method.

### PR DESCRIPTION
**Pull request by ketankr9**
**module/python** (python_destination)
Now init is optional in python destination.
These changes were made by taking help from similar deinit method.
Signed-off-by: Utsav Krishnan <utsav.krishnan.cse15@iitbhu.ac.in>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by bazsi** [comment]
@kira-syslogng ok to test

**Comment by furiel** [comment]
As I understand, this patch makes the init method optional indeed. However we lose an important behaviour: if there is an init method in python but returns false, it means the python module could not be initialized. In that case the pipe element should not be initialized either, as the python module is not ready to handle messages. As of this, syslog-ng should not start. Could you resolve this issue?

**Comment by ketankr9** [comment]
@furiel Yeah right. As of now the code runs even if the init returns false, let me look into this.

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

File: modules/python/python-dest.c [hunk 1]
```diff
@@ -267,7 +267,15 @@ _py_free_bindings(PythonDestDriver *self)
 
 static gboolean
 _py_init_object(PythonDestDriver *self)
-{
+{   
+  if (!_py_get_attr_or_null(self->py.instance, "init"))
+    {
+      msg_error("Missing Python method, init()",
```
Comment (Kokan) [inline modules/python/python-dest.c]: The modification aims is to make the `init` function optional, therefore I think it is not appropriate to write error logs, if the `init` is missing. You could use `debug` level for this.

File: modules/python/python-dest.c [hunk 2]
```diff
@@ -433,8 +441,8 @@ python_dd_init(LogPipe *d)
   gstate = PyGILState_Ensure();
 
   _py_perform_imports(self->loaders);
-  if (!_py_init_bindings(self) ||
-      !_py_init_object(self))
+  if (!_py_init_bindings(self)||
```
Comment (Kokan) [inline modules/python/python-dest.c]: This two line has only whitespace changes, it should not have.

File: modules/python/python-dest.c (hunk 1 above)
Comment (ketankr9) [reply modules/python/python-dest.c]: done.

File: modules/python/python-dest.c (hunk 2 above)
Comment (ketankr9) [reply modules/python/python-dest.c]: done.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by MrAnno** [comment]
Hi @ketankr9,

Thanks again for your contribution.

If I'm not mistaken, only 2 minor tasks remained before accepting your pull request:

1. remove trailing whitespaces from [here](https://travis-ci.org/balabit/syslog-ng/jobs/348341478#L487) (this will make Travis CI green)
2. **squash your commits** (we usually use `git rebase` when working on local branches) and choose a descriptive commit message fitting the following pattern:
```
module-name: short description

Your can explain your patch in more details here (optional).

Signed-off-by: Name <email>
```

An example:
```
python: make init() optional for destinations

Fixes #1756

Signed-off-by: Utsav Krishnan <utsav.krishnan.cse15@iitbhu.ac.in>
```

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions
